//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.20 at 04:03:32 PM MST 
//


package com.syml.filogix;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Full street address components
 * 
 * <p>Java class for Address1Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Address1Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="unitNumber" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="streetNumber" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="streetName" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="streetTypeDd" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="4"/>
 *               &lt;fractionDigits value="0"/>
 *               &lt;minExclusive value="-1"/>
 *               &lt;maxExclusive value="10000"/>
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *               &lt;enumeration value="3"/>
 *               &lt;enumeration value="4"/>
 *               &lt;enumeration value="5"/>
 *               &lt;enumeration value="6"/>
 *               &lt;enumeration value="7"/>
 *               &lt;enumeration value="8"/>
 *               &lt;enumeration value="9"/>
 *               &lt;enumeration value="10"/>
 *               &lt;enumeration value="11"/>
 *               &lt;enumeration value="12"/>
 *               &lt;enumeration value="13"/>
 *               &lt;enumeration value="14"/>
 *               &lt;enumeration value="15"/>
 *               &lt;enumeration value="16"/>
 *               &lt;enumeration value="17"/>
 *               &lt;enumeration value="18"/>
 *               &lt;enumeration value="19"/>
 *               &lt;enumeration value="20"/>
 *               &lt;enumeration value="21"/>
 *               &lt;enumeration value="22"/>
 *               &lt;enumeration value="23"/>
 *               &lt;enumeration value="24"/>
 *               &lt;enumeration value="25"/>
 *               &lt;enumeration value="26"/>
 *               &lt;enumeration value="27"/>
 *               &lt;enumeration value="28"/>
 *               &lt;enumeration value="29"/>
 *               &lt;enumeration value="30"/>
 *               &lt;enumeration value="31"/>
 *               &lt;enumeration value="32"/>
 *               &lt;enumeration value="33"/>
 *               &lt;enumeration value="34"/>
 *               &lt;enumeration value="35"/>
 *               &lt;enumeration value="36"/>
 *               &lt;enumeration value="37"/>
 *               &lt;enumeration value="38"/>
 *               &lt;enumeration value="39"/>
 *               &lt;enumeration value="40"/>
 *               &lt;enumeration value="41"/>
 *               &lt;enumeration value="42"/>
 *               &lt;enumeration value="43"/>
 *               &lt;enumeration value="44"/>
 *               &lt;enumeration value="45"/>
 *               &lt;enumeration value="46"/>
 *               &lt;enumeration value="47"/>
 *               &lt;enumeration value="48"/>
 *               &lt;enumeration value="49"/>
 *               &lt;enumeration value="50"/>
 *               &lt;enumeration value="51"/>
 *               &lt;enumeration value="52"/>
 *               &lt;enumeration value="53"/>
 *               &lt;enumeration value="54"/>
 *               &lt;enumeration value="55"/>
 *               &lt;enumeration value="56"/>
 *               &lt;enumeration value="57"/>
 *               &lt;enumeration value="58"/>
 *               &lt;enumeration value="59"/>
 *               &lt;enumeration value="60"/>
 *               &lt;enumeration value="61"/>
 *               &lt;enumeration value="62"/>
 *               &lt;enumeration value="63"/>
 *               &lt;enumeration value="64"/>
 *               &lt;enumeration value="65"/>
 *               &lt;enumeration value="66"/>
 *               &lt;enumeration value="67"/>
 *               &lt;enumeration value="68"/>
 *               &lt;enumeration value="69"/>
 *               &lt;enumeration value="70"/>
 *               &lt;enumeration value="71"/>
 *               &lt;enumeration value="72"/>
 *               &lt;enumeration value="73"/>
 *               &lt;enumeration value="74"/>
 *               &lt;enumeration value="75"/>
 *               &lt;enumeration value="76"/>
 *               &lt;enumeration value="77"/>
 *               &lt;enumeration value="78"/>
 *               &lt;enumeration value="79"/>
 *               &lt;enumeration value="80"/>
 *               &lt;enumeration value="81"/>
 *               &lt;enumeration value="82"/>
 *               &lt;enumeration value="83"/>
 *               &lt;enumeration value="84"/>
 *               &lt;enumeration value="85"/>
 *               &lt;enumeration value="86"/>
 *               &lt;enumeration value="87"/>
 *               &lt;enumeration value="88"/>
 *               &lt;enumeration value="89"/>
 *               &lt;enumeration value="90"/>
 *               &lt;enumeration value="91"/>
 *               &lt;enumeration value="92"/>
 *               &lt;enumeration value="93"/>
 *               &lt;enumeration value="94"/>
 *               &lt;enumeration value="95"/>
 *               &lt;enumeration value="96"/>
 *               &lt;enumeration value="97"/>
 *               &lt;enumeration value="98"/>
 *               &lt;enumeration value="99"/>
 *               &lt;enumeration value="100"/>
 *               &lt;enumeration value="101"/>
 *               &lt;enumeration value="102"/>
 *               &lt;enumeration value="103"/>
 *               &lt;enumeration value="104"/>
 *               &lt;enumeration value="105"/>
 *               &lt;enumeration value="106"/>
 *               &lt;enumeration value="107"/>
 *               &lt;enumeration value="108"/>
 *               &lt;enumeration value="109"/>
 *               &lt;enumeration value="110"/>
 *               &lt;enumeration value="111"/>
 *               &lt;enumeration value="112"/>
 *               &lt;enumeration value="113"/>
 *               &lt;enumeration value="114"/>
 *               &lt;enumeration value="115"/>
 *               &lt;enumeration value="116"/>
 *               &lt;enumeration value="117"/>
 *               &lt;enumeration value="118"/>
 *               &lt;enumeration value="119"/>
 *               &lt;enumeration value="120"/>
 *               &lt;enumeration value="121"/>
 *               &lt;enumeration value="122"/>
 *               &lt;enumeration value="123"/>
 *               &lt;enumeration value="124"/>
 *               &lt;enumeration value="125"/>
 *               &lt;enumeration value="126"/>
 *               &lt;enumeration value="127"/>
 *               &lt;enumeration value="128"/>
 *               &lt;enumeration value="129"/>
 *               &lt;enumeration value="130"/>
 *               &lt;enumeration value="131"/>
 *               &lt;enumeration value="132"/>
 *               &lt;enumeration value="133"/>
 *               &lt;enumeration value="134"/>
 *               &lt;enumeration value="135"/>
 *               &lt;enumeration value="136"/>
 *               &lt;enumeration value="137"/>
 *               &lt;enumeration value="138"/>
 *               &lt;enumeration value="139"/>
 *               &lt;enumeration value="140"/>
 *               &lt;enumeration value="141"/>
 *               &lt;enumeration value="142"/>
 *               &lt;enumeration value="201"/>
 *               &lt;enumeration value="202"/>
 *               &lt;enumeration value="203"/>
 *               &lt;enumeration value="204"/>
 *               &lt;enumeration value="205"/>
 *               &lt;enumeration value="206"/>
 *               &lt;enumeration value="207"/>
 *               &lt;enumeration value="208"/>
 *               &lt;enumeration value="209"/>
 *               &lt;enumeration value="210"/>
 *               &lt;enumeration value="211"/>
 *               &lt;enumeration value="212"/>
 *               &lt;enumeration value="213"/>
 *               &lt;enumeration value="214"/>
 *               &lt;enumeration value="215"/>
 *               &lt;enumeration value="216"/>
 *               &lt;enumeration value="217"/>
 *               &lt;enumeration value="218"/>
 *               &lt;enumeration value="219"/>
 *               &lt;enumeration value="220"/>
 *               &lt;enumeration value="221"/>
 *               &lt;enumeration value="222"/>
 *               &lt;enumeration value="223"/>
 *               &lt;enumeration value="224"/>
 *               &lt;enumeration value="225"/>
 *               &lt;enumeration value="226"/>
 *               &lt;enumeration value="227"/>
 *               &lt;enumeration value="228"/>
 *               &lt;enumeration value="229"/>
 *               &lt;enumeration value="230"/>
 *               &lt;enumeration value="231"/>
 *               &lt;enumeration value="232"/>
 *               &lt;enumeration value="233"/>
 *               &lt;enumeration value="234"/>
 *               &lt;enumeration value="235"/>
 *               &lt;enumeration value="236"/>
 *               &lt;enumeration value="237"/>
 *               &lt;enumeration value="238"/>
 *               &lt;enumeration value="239"/>
 *               &lt;enumeration value="240"/>
 *               &lt;enumeration value="241"/>
 *               &lt;enumeration value="242"/>
 *               &lt;enumeration value="243"/>
 *               &lt;enumeration value="244"/>
 *               &lt;enumeration value="245"/>
 *               &lt;enumeration value="246"/>
 *               &lt;enumeration value="247"/>
 *               &lt;enumeration value="248"/>
 *               &lt;enumeration value="249"/>
 *               &lt;enumeration value="250"/>
 *               &lt;enumeration value="251"/>
 *               &lt;enumeration value="252"/>
 *               &lt;enumeration value="253"/>
 *               &lt;enumeration value="254"/>
 *               &lt;enumeration value="255"/>
 *               &lt;enumeration value="256"/>
 *               &lt;enumeration value="257"/>
 *               &lt;enumeration value="258"/>
 *               &lt;enumeration value="259"/>
 *               &lt;enumeration value="260"/>
 *               &lt;enumeration value="261"/>
 *               &lt;enumeration value="262"/>
 *               &lt;enumeration value="263"/>
 *               &lt;enumeration value="264"/>
 *               &lt;enumeration value="265"/>
 *               &lt;enumeration value="266"/>
 *               &lt;enumeration value="267"/>
 *               &lt;enumeration value="268"/>
 *               &lt;enumeration value="269"/>
 *               &lt;enumeration value="270"/>
 *               &lt;enumeration value="271"/>
 *               &lt;enumeration value="272"/>
 *               &lt;enumeration value="273"/>
 *               &lt;enumeration value="274"/>
 *               &lt;enumeration value="275"/>
 *               &lt;enumeration value="276"/>
 *               &lt;enumeration value="277"/>
 *               &lt;enumeration value="278"/>
 *               &lt;enumeration value="279"/>
 *               &lt;enumeration value="280"/>
 *               &lt;enumeration value="281"/>
 *               &lt;enumeration value="282"/>
 *               &lt;enumeration value="283"/>
 *               &lt;enumeration value="284"/>
 *               &lt;enumeration value="285"/>
 *               &lt;enumeration value="286"/>
 *               &lt;enumeration value="287"/>
 *               &lt;enumeration value="288"/>
 *               &lt;enumeration value="289"/>
 *               &lt;enumeration value="290"/>
 *               &lt;enumeration value="291"/>
 *               &lt;enumeration value="292"/>
 *               &lt;enumeration value="293"/>
 *               &lt;enumeration value="294"/>
 *               &lt;enumeration value="295"/>
 *               &lt;enumeration value="296"/>
 *               &lt;enumeration value="297"/>
 *               &lt;enumeration value="298"/>
 *               &lt;enumeration value="299"/>
 *               &lt;enumeration value="300"/>
 *               &lt;enumeration value="301"/>
 *               &lt;enumeration value="302"/>
 *               &lt;enumeration value="303"/>
 *               &lt;enumeration value="304"/>
 *               &lt;enumeration value="305"/>
 *               &lt;enumeration value="306"/>
 *               &lt;enumeration value="307"/>
 *               &lt;enumeration value="308"/>
 *               &lt;enumeration value="309"/>
 *               &lt;enumeration value="310"/>
 *               &lt;enumeration value="311"/>
 *               &lt;enumeration value="312"/>
 *               &lt;enumeration value="313"/>
 *               &lt;enumeration value="314"/>
 *               &lt;enumeration value="315"/>
 *               &lt;enumeration value="316"/>
 *               &lt;enumeration value="317"/>
 *               &lt;enumeration value="318"/>
 *               &lt;enumeration value="319"/>
 *               &lt;enumeration value="320"/>
 *               &lt;enumeration value="321"/>
 *               &lt;enumeration value="322"/>
 *               &lt;enumeration value="323"/>
 *               &lt;enumeration value="324"/>
 *               &lt;enumeration value="325"/>
 *               &lt;enumeration value="326"/>
 *               &lt;enumeration value="327"/>
 *               &lt;enumeration value="328"/>
 *               &lt;enumeration value="329"/>
 *               &lt;enumeration value="330"/>
 *               &lt;enumeration value="331"/>
 *               &lt;enumeration value="332"/>
 *               &lt;enumeration value="333"/>
 *               &lt;enumeration value="334"/>
 *               &lt;enumeration value="335"/>
 *               &lt;enumeration value="336"/>
 *               &lt;enumeration value="337"/>
 *               &lt;enumeration value="338"/>
 *               &lt;enumeration value="339"/>
 *               &lt;enumeration value="340"/>
 *               &lt;enumeration value="341"/>
 *               &lt;enumeration value="342"/>
 *               &lt;enumeration value="343"/>
 *               &lt;enumeration value="344"/>
 *               &lt;enumeration value="345"/>
 *               &lt;enumeration value="346"/>
 *               &lt;enumeration value="347"/>
 *               &lt;enumeration value="348"/>
 *               &lt;enumeration value="349"/>
 *               &lt;enumeration value="350"/>
 *               &lt;enumeration value="351"/>
 *               &lt;enumeration value="352"/>
 *               &lt;enumeration value="353"/>
 *               &lt;enumeration value="354"/>
 *               &lt;enumeration value="355"/>
 *               &lt;enumeration value="356"/>
 *               &lt;enumeration value="357"/>
 *               &lt;enumeration value="358"/>
 *               &lt;enumeration value="359"/>
 *               &lt;enumeration value="360"/>
 *               &lt;enumeration value="361"/>
 *               &lt;enumeration value="362"/>
 *               &lt;enumeration value="363"/>
 *               &lt;enumeration value="364"/>
 *               &lt;enumeration value="365"/>
 *               &lt;enumeration value="366"/>
 *               &lt;enumeration value="367"/>
 *               &lt;enumeration value="368"/>
 *               &lt;enumeration value="369"/>
 *               &lt;enumeration value="370"/>
 *               &lt;enumeration value="371"/>
 *               &lt;enumeration value="372"/>
 *               &lt;enumeration value="373"/>
 *               &lt;enumeration value="374"/>
 *               &lt;enumeration value="375"/>
 *               &lt;enumeration value="376"/>
 *               &lt;enumeration value="377"/>
 *               &lt;enumeration value="378"/>
 *               &lt;enumeration value="379"/>
 *               &lt;enumeration value="380"/>
 *               &lt;enumeration value="381"/>
 *               &lt;enumeration value="382"/>
 *               &lt;enumeration value="383"/>
 *               &lt;enumeration value="384"/>
 *               &lt;enumeration value="385"/>
 *               &lt;enumeration value="386"/>
 *               &lt;enumeration value="387"/>
 *               &lt;enumeration value="388"/>
 *               &lt;enumeration value="389"/>
 *               &lt;enumeration value="390"/>
 *               &lt;enumeration value="391"/>
 *               &lt;enumeration value="392"/>
 *               &lt;enumeration value="393"/>
 *               &lt;enumeration value="394"/>
 *               &lt;enumeration value="395"/>
 *               &lt;enumeration value="396"/>
 *               &lt;enumeration value="397"/>
 *               &lt;enumeration value="398"/>
 *               &lt;enumeration value="399"/>
 *               &lt;enumeration value="400"/>
 *               &lt;enumeration value="401"/>
 *               &lt;enumeration value="402"/>
 *               &lt;enumeration value="403"/>
 *               &lt;enumeration value="404"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="streetDirectionDd" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="2"/>
 *               &lt;fractionDigits value="0"/>
 *               &lt;minExclusive value="-1"/>
 *               &lt;maxExclusive value="100"/>
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *               &lt;enumeration value="3"/>
 *               &lt;enumeration value="4"/>
 *               &lt;enumeration value="5"/>
 *               &lt;enumeration value="6"/>
 *               &lt;enumeration value="7"/>
 *               &lt;enumeration value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="city" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="provinceDd" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="2"/>
 *               &lt;fractionDigits value="0"/>
 *               &lt;minExclusive value="-1"/>
 *               &lt;maxExclusive value="100"/>
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *               &lt;enumeration value="3"/>
 *               &lt;enumeration value="4"/>
 *               &lt;enumeration value="5"/>
 *               &lt;enumeration value="6"/>
 *               &lt;enumeration value="7"/>
 *               &lt;enumeration value="8"/>
 *               &lt;enumeration value="9"/>
 *               &lt;enumeration value="10"/>
 *               &lt;enumeration value="11"/>
 *               &lt;enumeration value="12"/>
 *               &lt;enumeration value="13"/>
 *               &lt;enumeration value="20"/>
 *               &lt;enumeration value="21"/>
 *               &lt;enumeration value="22"/>
 *               &lt;enumeration value="23"/>
 *               &lt;enumeration value="24"/>
 *               &lt;enumeration value="25"/>
 *               &lt;enumeration value="26"/>
 *               &lt;enumeration value="27"/>
 *               &lt;enumeration value="28"/>
 *               &lt;enumeration value="29"/>
 *               &lt;enumeration value="30"/>
 *               &lt;enumeration value="31"/>
 *               &lt;enumeration value="32"/>
 *               &lt;enumeration value="33"/>
 *               &lt;enumeration value="34"/>
 *               &lt;enumeration value="35"/>
 *               &lt;enumeration value="36"/>
 *               &lt;enumeration value="37"/>
 *               &lt;enumeration value="38"/>
 *               &lt;enumeration value="39"/>
 *               &lt;enumeration value="40"/>
 *               &lt;enumeration value="41"/>
 *               &lt;enumeration value="42"/>
 *               &lt;enumeration value="43"/>
 *               &lt;enumeration value="44"/>
 *               &lt;enumeration value="45"/>
 *               &lt;enumeration value="46"/>
 *               &lt;enumeration value="47"/>
 *               &lt;enumeration value="48"/>
 *               &lt;enumeration value="49"/>
 *               &lt;enumeration value="50"/>
 *               &lt;enumeration value="51"/>
 *               &lt;enumeration value="52"/>
 *               &lt;enumeration value="53"/>
 *               &lt;enumeration value="54"/>
 *               &lt;enumeration value="55"/>
 *               &lt;enumeration value="56"/>
 *               &lt;enumeration value="57"/>
 *               &lt;enumeration value="58"/>
 *               &lt;enumeration value="59"/>
 *               &lt;enumeration value="60"/>
 *               &lt;enumeration value="61"/>
 *               &lt;enumeration value="62"/>
 *               &lt;enumeration value="63"/>
 *               &lt;enumeration value="64"/>
 *               &lt;enumeration value="65"/>
 *               &lt;enumeration value="66"/>
 *               &lt;enumeration value="67"/>
 *               &lt;enumeration value="68"/>
 *               &lt;enumeration value="69"/>
 *               &lt;enumeration value="70"/>
 *               &lt;enumeration value="71"/>
 *               &lt;enumeration value="72"/>
 *               &lt;enumeration value="73"/>
 *               &lt;enumeration value="74"/>
 *               &lt;enumeration value="75"/>
 *               &lt;enumeration value="76"/>
 *               &lt;enumeration value="77"/>
 *               &lt;enumeration value="78"/>
 *               &lt;enumeration value="79"/>
 *               &lt;enumeration value="80"/>
 *               &lt;enumeration value="81"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="internationalPostalCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="postalFsa" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="postalLdu" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="countryTypeDd" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="6"/>
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Address1Type", propOrder = {
    "unitNumber",
    "streetNumber",
    "streetName",
    "streetTypeDd",
    "streetDirectionDd",
    "city",
    "provinceDd",
    "internationalPostalCode",
    "postalFsa",
    "postalLdu",
    "countryTypeDd"
})
public class Address1Type {

    protected String unitNumber;
    protected String streetNumber;
    protected String streetName;
    protected BigDecimal streetTypeDd;
    protected BigDecimal streetDirectionDd;
    protected String city;
    protected BigDecimal provinceDd;
    protected String internationalPostalCode;
    protected String postalFsa;
    protected String postalLdu;
    protected String countryTypeDd;

    /**
     * Gets the value of the unitNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitNumber() {
        return unitNumber;
    }

    /**
     * Sets the value of the unitNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitNumber(String value) {
        this.unitNumber = value;
    }

    /**
     * Gets the value of the streetNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetNumber() {
        return streetNumber;
    }

    /**
     * Sets the value of the streetNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetNumber(String value) {
        this.streetNumber = value;
    }

    /**
     * Gets the value of the streetName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetName() {
        return streetName;
    }

    /**
     * Sets the value of the streetName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetName(String value) {
        this.streetName = value;
    }

    /**
     * Gets the value of the streetTypeDd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStreetTypeDd() {
        return streetTypeDd;
    }

    /**
     * Sets the value of the streetTypeDd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStreetTypeDd(BigDecimal value) {
        this.streetTypeDd = value;
    }

    /**
     * Gets the value of the streetDirectionDd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStreetDirectionDd() {
        return streetDirectionDd;
    }

    /**
     * Sets the value of the streetDirectionDd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStreetDirectionDd(BigDecimal value) {
        this.streetDirectionDd = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the provinceDd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getProvinceDd() {
        return provinceDd;
    }

    /**
     * Sets the value of the provinceDd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setProvinceDd(BigDecimal value) {
        this.provinceDd = value;
    }

    /**
     * Gets the value of the internationalPostalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternationalPostalCode() {
        return internationalPostalCode;
    }

    /**
     * Sets the value of the internationalPostalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternationalPostalCode(String value) {
        this.internationalPostalCode = value;
    }

    /**
     * Gets the value of the postalFsa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostalFsa() {
        return postalFsa;
    }

    /**
     * Sets the value of the postalFsa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostalFsa(String value) {
        this.postalFsa = value;
    }

    /**
     * Gets the value of the postalLdu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostalLdu() {
        return postalLdu;
    }

    /**
     * Sets the value of the postalLdu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostalLdu(String value) {
        this.postalLdu = value;
    }

    /**
     * Gets the value of the countryTypeDd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryTypeDd() {
        return countryTypeDd;
    }

    /**
     * Sets the value of the countryTypeDd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryTypeDd(String value) {
        this.countryTypeDd = value;
    }

    @Override
    public String toString() {
        return "Address1Type [unitNumber=" + unitNumber + ", streetNumber=" + streetNumber + ", streetName="
                + streetName + ", streetTypeDd=" + streetTypeDd + ", streetDirectionDd=" + streetDirectionDd + ", city="
                + city + ", provinceDd=" + provinceDd + ", internationalPostalCode=" + internationalPostalCode
                + ", postalFsa=" + postalFsa + ", postalLdu=" + postalLdu + ", countryTypeDd=" + countryTypeDd + "]";
    }

}
