//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.20 at 04:03:32 PM MST 
//


package com.syml.filogix;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BaseApplicantType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BaseApplicantType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.filogix.com/Schema/FCXAPI/1}BasePersonType">
 *       &lt;sequence>
 *         &lt;element name="addressDetail" type="{http://www.filogix.com/Schema/FCXAPI/1}ApplicantAddressType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="bankruptcyStatusDd" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="2"/>
 *               &lt;fractionDigits value="0"/>
 *               &lt;minExclusive value="-1"/>
 *               &lt;maxExclusive value="100"/>
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="citizenshipTypeDd" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="2"/>
 *               &lt;fractionDigits value="0"/>
 *               &lt;minExclusive value="-1"/>
 *               &lt;maxExclusive value="100"/>
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *               &lt;enumeration value="3"/>
 *               &lt;enumeration value="4"/>
 *               &lt;enumeration value="5"/>
 *               &lt;enumeration value="6"/>
 *               &lt;enumeration value="7"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="clientReferenceNumber" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="employeeNumber" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="35"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="existingClient" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value="Y"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="firstTimeBuyer" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value="Y"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="isEmployeeDd" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="2"/>
 *               &lt;fractionDigits value="0"/>
 *               &lt;minExclusive value="-1"/>
 *               &lt;maxExclusive value="100"/>
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="identification" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="identificationNumber" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="30"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="identificationCountry" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="30"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="identificationTypeDd" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                         &lt;totalDigits value="2"/>
 *                         &lt;fractionDigits value="0"/>
 *                         &lt;minExclusive value="-1"/>
 *                         &lt;maxExclusive value="100"/>
 *                         &lt;enumeration value="10"/>
 *                         &lt;enumeration value="11"/>
 *                         &lt;enumeration value="12"/>
 *                         &lt;enumeration value="13"/>
 *                         &lt;enumeration value="14"/>
 *                         &lt;enumeration value="30"/>
 *                         &lt;enumeration value="31"/>
 *                         &lt;enumeration value="32"/>
 *                         &lt;enumeration value="33"/>
 *                         &lt;enumeration value="34"/>
 *                         &lt;enumeration value="35"/>
 *                         &lt;enumeration value="36"/>
 *                         &lt;enumeration value="50"/>
 *                         &lt;enumeration value="51"/>
 *                         &lt;enumeration value="52"/>
 *                         &lt;enumeration value="53"/>
 *                         &lt;enumeration value="54"/>
 *                         &lt;enumeration value="55"/>
 *                         &lt;enumeration value="56"/>
 *                         &lt;enumeration value="57"/>
 *                         &lt;enumeration value="58"/>
 *                         &lt;enumeration value="70"/>
 *                         &lt;enumeration value="71"/>
 *                         &lt;enumeration value="72"/>
 *                         &lt;enumeration value="73"/>
 *                         &lt;enumeration value="90"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="relationshipToPrimaryApplicant" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *               &lt;enumeration value="3"/>
 *               &lt;enumeration value="4"/>
 *               &lt;enumeration value="5"/>
 *               &lt;enumeration value="6"/>
 *               &lt;enumeration value="7"/>
 *               &lt;enumeration value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseApplicantType", propOrder = {
    "addressDetail",
    "bankruptcyStatusDd",
    "citizenshipTypeDd",
    "clientReferenceNumber",
    "employeeNumber",
    "existingClient",
    "firstTimeBuyer",
    "isEmployeeDd",
    "identification",
    "relationshipToPrimaryApplicant"
})
@XmlSeeAlso({
    ApplicantApplicationType.class
})
public class BaseApplicantType
    extends BasePersonType
{

    protected List<ApplicantAddressType> addressDetail;
    protected BigDecimal bankruptcyStatusDd;
    protected BigDecimal citizenshipTypeDd;
    protected String clientReferenceNumber;
    protected String employeeNumber;
    protected String existingClient;
    protected String firstTimeBuyer;
    protected BigDecimal isEmployeeDd;
    protected List<BaseApplicantType.Identification> identification;
    protected String relationshipToPrimaryApplicant;

    /**
     * Gets the value of the addressDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addressDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddressDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ApplicantAddressType }
     * 
     * 
     */
    public List<ApplicantAddressType> getAddressDetail() {
        if (addressDetail == null) {
            addressDetail = new ArrayList<ApplicantAddressType>();
        }
        return this.addressDetail;
    }

    /**
     * Gets the value of the bankruptcyStatusDd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBankruptcyStatusDd() {
        return bankruptcyStatusDd;
    }

    /**
     * Sets the value of the bankruptcyStatusDd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBankruptcyStatusDd(BigDecimal value) {
        this.bankruptcyStatusDd = value;
    }

    /**
     * Gets the value of the citizenshipTypeDd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCitizenshipTypeDd() {
        return citizenshipTypeDd;
    }

    /**
     * Sets the value of the citizenshipTypeDd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCitizenshipTypeDd(BigDecimal value) {
        this.citizenshipTypeDd = value;
    }

    /**
     * Gets the value of the clientReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientReferenceNumber() {
        return clientReferenceNumber;
    }

    /**
     * Sets the value of the clientReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientReferenceNumber(String value) {
        this.clientReferenceNumber = value;
    }

    /**
     * Gets the value of the employeeNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeNumber() {
        return employeeNumber;
    }

    /**
     * Sets the value of the employeeNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeNumber(String value) {
        this.employeeNumber = value;
    }

    /**
     * Gets the value of the existingClient property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExistingClient() {
        return existingClient;
    }

    /**
     * Sets the value of the existingClient property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExistingClient(String value) {
        this.existingClient = value;
    }

    /**
     * Gets the value of the firstTimeBuyer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstTimeBuyer() {
        return firstTimeBuyer;
    }

    /**
     * Sets the value of the firstTimeBuyer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstTimeBuyer(String value) {
        this.firstTimeBuyer = value;
    }

    /**
     * Gets the value of the isEmployeeDd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIsEmployeeDd() {
        return isEmployeeDd;
    }

    /**
     * Sets the value of the isEmployeeDd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIsEmployeeDd(BigDecimal value) {
        this.isEmployeeDd = value;
    }

    /**
     * Gets the value of the identification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BaseApplicantType.Identification }
     * 
     * 
     */
    public List<BaseApplicantType.Identification> getIdentification() {
        if (identification == null) {
            identification = new ArrayList<BaseApplicantType.Identification>();
        }
        return this.identification;
    }

    /**
     * Gets the value of the relationshipToPrimaryApplicant property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelationshipToPrimaryApplicant() {
        return relationshipToPrimaryApplicant;
    }

    /**
     * Sets the value of the relationshipToPrimaryApplicant property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelationshipToPrimaryApplicant(String value) {
        this.relationshipToPrimaryApplicant = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="identificationNumber" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="30"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="identificationCountry" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="30"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="identificationTypeDd" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *               &lt;totalDigits value="2"/>
     *               &lt;fractionDigits value="0"/>
     *               &lt;minExclusive value="-1"/>
     *               &lt;maxExclusive value="100"/>
     *               &lt;enumeration value="10"/>
     *               &lt;enumeration value="11"/>
     *               &lt;enumeration value="12"/>
     *               &lt;enumeration value="13"/>
     *               &lt;enumeration value="14"/>
     *               &lt;enumeration value="30"/>
     *               &lt;enumeration value="31"/>
     *               &lt;enumeration value="32"/>
     *               &lt;enumeration value="33"/>
     *               &lt;enumeration value="34"/>
     *               &lt;enumeration value="35"/>
     *               &lt;enumeration value="36"/>
     *               &lt;enumeration value="50"/>
     *               &lt;enumeration value="51"/>
     *               &lt;enumeration value="52"/>
     *               &lt;enumeration value="53"/>
     *               &lt;enumeration value="54"/>
     *               &lt;enumeration value="55"/>
     *               &lt;enumeration value="56"/>
     *               &lt;enumeration value="57"/>
     *               &lt;enumeration value="58"/>
     *               &lt;enumeration value="70"/>
     *               &lt;enumeration value="71"/>
     *               &lt;enumeration value="72"/>
     *               &lt;enumeration value="73"/>
     *               &lt;enumeration value="90"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "identificationNumber",
        "identificationCountry",
        "identificationTypeDd"
    })
    public static class Identification {

        protected String identificationNumber;
        protected String identificationCountry;
        protected BigDecimal identificationTypeDd;

        /**
         * Gets the value of the identificationNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdentificationNumber() {
            return identificationNumber;
        }

        /**
         * Sets the value of the identificationNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdentificationNumber(String value) {
            this.identificationNumber = value;
        }

        /**
         * Gets the value of the identificationCountry property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdentificationCountry() {
            return identificationCountry;
        }

        /**
         * Sets the value of the identificationCountry property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdentificationCountry(String value) {
            this.identificationCountry = value;
        }

        /**
         * Gets the value of the identificationTypeDd property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getIdentificationTypeDd() {
            return identificationTypeDd;
        }

        /**
         * Sets the value of the identificationTypeDd property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setIdentificationTypeDd(BigDecimal value) {
            this.identificationTypeDd = value;
        }

    }

}
