//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.20 at 04:03:32 PM MST 
//


package com.syml.filogix;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Contact Node for Address type 1 (full address)
 * 
 * <p>Java class for ContactTypeAddresstype1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContactTypeAddresstype1">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.filogix.com/Schema/FCXAPI/1}ContactTypeBase">
 *       &lt;sequence>
 *         &lt;element name="address" type="{http://www.filogix.com/Schema/FCXAPI/1}Address1Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContactTypeAddresstype1", propOrder = {
    "address"
})
public class ContactTypeAddresstype1
    extends ContactTypeBase
{

    protected Address1Type address;

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link Address1Type }
     *     
     */
    public Address1Type getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address1Type }
     *     
     */
    public void setAddress(Address1Type value) {
        this.address = value;
    }

}
