//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.20 at 04:03:32 PM MST 
//


package com.syml.filogix;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PropertyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="actualAppraisalValue" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="13"/>
 *               &lt;fractionDigits value="2"/>
 *               &lt;minExclusive value="-100000000000"/>
 *               &lt;maxExclusive value="100000000000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="address" type="{http://www.filogix.com/Schema/FCXAPI/1}Address1Type" minOccurs="0"/>
 *         &lt;element name="appraisalDateAct" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}dateTime">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="builderName" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="80"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="dwellingStyleDd" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="2"/>
 *               &lt;fractionDigits value="0"/>
 *               &lt;minExclusive value="-1"/>
 *               &lt;maxExclusive value="100"/>
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *               &lt;enumeration value="3"/>
 *               &lt;enumeration value="4"/>
 *               &lt;enumeration value="5"/>
 *               &lt;enumeration value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="dwellingTypeDd" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="2"/>
 *               &lt;fractionDigits value="0"/>
 *               &lt;minExclusive value="-1"/>
 *               &lt;maxExclusive value="100"/>
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *               &lt;enumeration value="3"/>
 *               &lt;enumeration value="4"/>
 *               &lt;enumeration value="5"/>
 *               &lt;enumeration value="6"/>
 *               &lt;enumeration value="7"/>
 *               &lt;enumeration value="8"/>
 *               &lt;enumeration value="9"/>
 *               &lt;enumeration value="10"/>
 *               &lt;enumeration value="11"/>
 *               &lt;enumeration value="12"/>
 *               &lt;enumeration value="13"/>
 *               &lt;enumeration value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="estimatedAppraisalValue" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="13"/>
 *               &lt;fractionDigits value="2"/>
 *               &lt;minExclusive value="-100000000000"/>
 *               &lt;maxExclusive value="100000000000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="feesIncludeHeat" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value="Y"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="garageSizeDd" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="2"/>
 *               &lt;fractionDigits value="0"/>
 *               &lt;minExclusive value="-1"/>
 *               &lt;maxExclusive value="100"/>
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *               &lt;enumeration value="3"/>
 *               &lt;enumeration value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="garageTypeDd" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="2"/>
 *               &lt;fractionDigits value="0"/>
 *               &lt;minExclusive value="-1"/>
 *               &lt;maxExclusive value="100"/>
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="heatTypeDd" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="2"/>
 *               &lt;fractionDigits value="0"/>
 *               &lt;minExclusive value="-1"/>
 *               &lt;maxExclusive value="100"/>
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *               &lt;enumeration value="3"/>
 *               &lt;enumeration value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="includetds" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value="Y"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="rentalIncome" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.filogix.com/Schema/FCXAPI/1}IncomeType">
 *                 &lt;sequence>
 *                   &lt;element name="incomeTypeDd" type="{http://www.filogix.com/Schema/FCXAPI/1}incomeTypeRentalDd"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="insulatedWithUffi" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value="Y"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="legalLine1" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="35"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="legalLine2" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="35"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="legalLine3" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="35"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="livingSpace" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;totalDigits value="8"/>
 *               &lt;maxExclusive value="100000000"/>
 *               &lt;minExclusive value="-1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="livingSpaceUnitOfMeasurDd" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="2"/>
 *               &lt;fractionDigits value="0"/>
 *               &lt;minExclusive value="-1"/>
 *               &lt;maxExclusive value="100"/>
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="lotSize" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;totalDigits value="8"/>
 *               &lt;maxExclusive value="100000000"/>
 *               &lt;minExclusive value="-1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="lotSizeUnitOfMeasureDd" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="2"/>
 *               &lt;fractionDigits value="0"/>
 *               &lt;minExclusive value="-1"/>
 *               &lt;maxExclusive value="100"/>
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *               &lt;enumeration value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="mlsListingFlag" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value="Y"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="newConstructionDd" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="2"/>
 *               &lt;fractionDigits value="0"/>
 *               &lt;minExclusive value="-1"/>
 *               &lt;maxExclusive value="100"/>
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="numberOfUnits" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minExclusive value="0"/>
 *               &lt;maxExclusive value="1000"/>
 *               &lt;totalDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="occupancyTypeDd" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="2"/>
 *               &lt;fractionDigits value="0"/>
 *               &lt;minExclusive value="-1"/>
 *               &lt;maxExclusive value="100"/>
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *               &lt;enumeration value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="originalPurchasePrice" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="13"/>
 *               &lt;fractionDigits value="2"/>
 *               &lt;minExclusive value="-100000000000"/>
 *               &lt;maxExclusive value="100000000000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="propertyTypeDd" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="2"/>
 *               &lt;fractionDigits value="0"/>
 *               &lt;minExclusive value="-1"/>
 *               &lt;maxExclusive value="100"/>
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="purchasePrice" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="13"/>
 *               &lt;fractionDigits value="2"/>
 *               &lt;minExclusive value="-100000000000"/>
 *               &lt;maxExclusive value="100000000000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="refiOrigPurchaseDate" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}dateTime">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="sewageTypeDd" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="2"/>
 *               &lt;fractionDigits value="0"/>
 *               &lt;minExclusive value="-1"/>
 *               &lt;maxExclusive value="100"/>
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="structureAge" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minExclusive value="-1"/>
 *               &lt;maxExclusive value="1000"/>
 *               &lt;totalDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="taxationYear" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;totalDigits value="4"/>
 *               &lt;maxExclusive value="10000"/>
 *               &lt;minExclusive value="1950"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="waterTypeDd" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="2"/>
 *               &lt;fractionDigits value="0"/>
 *               &lt;minExclusive value="-1"/>
 *               &lt;maxExclusive value="100"/>
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="propertyExpense" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="propertyExpenseAmount">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                         &lt;totalDigits value="13"/>
 *                         &lt;fractionDigits value="2"/>
 *                         &lt;minExclusive value="-100000000000"/>
 *                         &lt;maxExclusive value="100000000000"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="propertyExpenseDescription" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="80"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="propertyExpensePeriodDd">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                         &lt;totalDigits value="13"/>
 *                         &lt;fractionDigits value="0"/>
 *                         &lt;minExclusive value="-1"/>
 *                         &lt;maxExclusive value="10000000000000"/>
 *                         &lt;enumeration value="0"/>
 *                         &lt;enumeration value="1"/>
 *                         &lt;enumeration value="2"/>
 *                         &lt;enumeration value="3"/>
 *                         &lt;enumeration value="4"/>
 *                         &lt;enumeration value="5"/>
 *                         &lt;enumeration value="6"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="propertyExpenseTypeDd">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                         &lt;totalDigits value="13"/>
 *                         &lt;fractionDigits value="0"/>
 *                         &lt;minExclusive value="-1"/>
 *                         &lt;maxExclusive value="10000000000000"/>
 *                         &lt;enumeration value="0"/>
 *                         &lt;enumeration value="1"/>
 *                         &lt;enumeration value="2"/>
 *                         &lt;enumeration value="3"/>
 *                         &lt;enumeration value="4"/>
 *                         &lt;enumeration value="5"/>
 *                         &lt;enumeration value="6"/>
 *                         &lt;enumeration value="7"/>
 *                         &lt;enumeration value="8"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="propertyadditionalData" type="{http://www.filogix.com/Schema/FCXAPI/1}AdditionalDataType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PropertyType", propOrder = {
    "actualAppraisalValue",
    "address",
    "appraisalDateAct",
    "builderName",
    "dwellingStyleDd",
    "dwellingTypeDd",
    "estimatedAppraisalValue",
    "feesIncludeHeat",
    "garageSizeDd",
    "garageTypeDd",
    "heatTypeDd",
    "includetds",
    "rentalIncome",
    "insulatedWithUffi",
    "legalLine1",
    "legalLine2",
    "legalLine3",
    "livingSpace",
    "livingSpaceUnitOfMeasurDd",
    "lotSize",
    "lotSizeUnitOfMeasureDd",
    "mlsListingFlag",
    "newConstructionDd",
    "numberOfUnits",
    "occupancyTypeDd",
    "originalPurchasePrice",
    "propertyTypeDd",
    "purchasePrice",
    "refiOrigPurchaseDate",
    "sewageTypeDd",
    "structureAge",
    "taxationYear",
    "waterTypeDd",
    "propertyExpense",
    "propertyadditionalData"
})
public class PropertyType {

    protected BigDecimal actualAppraisalValue;
    protected Address1Type address;
    protected XMLGregorianCalendar appraisalDateAct;
    protected String builderName;
    protected BigDecimal dwellingStyleDd;
    protected BigDecimal dwellingTypeDd;
    protected BigDecimal estimatedAppraisalValue;
    protected String feesIncludeHeat;
    protected BigDecimal garageSizeDd;
    protected BigDecimal garageTypeDd;
    protected BigDecimal heatTypeDd;
    protected String includetds;
    protected PropertyType.RentalIncome rentalIncome;
    protected String insulatedWithUffi;
    protected String legalLine1;
    protected String legalLine2;
    protected String legalLine3;
    protected Integer livingSpace;
    protected BigDecimal livingSpaceUnitOfMeasurDd;
    protected Integer lotSize;
    protected BigDecimal lotSizeUnitOfMeasureDd;
    protected String mlsListingFlag;
    protected BigDecimal newConstructionDd;
    protected Integer numberOfUnits;
    protected BigDecimal occupancyTypeDd;
    protected BigDecimal originalPurchasePrice;
    protected BigDecimal propertyTypeDd;
    protected BigDecimal purchasePrice;
    protected XMLGregorianCalendar refiOrigPurchaseDate;
    protected BigDecimal sewageTypeDd;
    protected Integer structureAge;
    protected Integer taxationYear;
    protected BigDecimal waterTypeDd;
    protected List<PropertyType.PropertyExpense> propertyExpense;
    protected List<AdditionalDataType> propertyadditionalData;

    /**
     * Gets the value of the actualAppraisalValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getActualAppraisalValue() {
        return actualAppraisalValue;
    }

    /**
     * Sets the value of the actualAppraisalValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setActualAppraisalValue(BigDecimal value) {
        this.actualAppraisalValue = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link Address1Type }
     *     
     */
    public Address1Type getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address1Type }
     *     
     */
    public void setAddress(Address1Type value) {
        this.address = value;
    }

    /**
     * Gets the value of the appraisalDateAct property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAppraisalDateAct() {
        return appraisalDateAct;
    }

    /**
     * Sets the value of the appraisalDateAct property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAppraisalDateAct(XMLGregorianCalendar value) {
        this.appraisalDateAct = value;
    }

    /**
     * Gets the value of the builderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuilderName() {
        return builderName;
    }

    /**
     * Sets the value of the builderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuilderName(String value) {
        this.builderName = value;
    }

    /**
     * Gets the value of the dwellingStyleDd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDwellingStyleDd() {
        return dwellingStyleDd;
    }

    /**
     * Sets the value of the dwellingStyleDd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDwellingStyleDd(BigDecimal value) {
        this.dwellingStyleDd = value;
    }

    /**
     * Gets the value of the dwellingTypeDd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDwellingTypeDd() {
        return dwellingTypeDd;
    }

    /**
     * Sets the value of the dwellingTypeDd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDwellingTypeDd(BigDecimal value) {
        this.dwellingTypeDd = value;
    }

    /**
     * Gets the value of the estimatedAppraisalValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEstimatedAppraisalValue() {
        return estimatedAppraisalValue;
    }

    /**
     * Sets the value of the estimatedAppraisalValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEstimatedAppraisalValue(BigDecimal value) {
        this.estimatedAppraisalValue = value;
    }

    /**
     * Gets the value of the feesIncludeHeat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeesIncludeHeat() {
        return feesIncludeHeat;
    }

    /**
     * Sets the value of the feesIncludeHeat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeesIncludeHeat(String value) {
        this.feesIncludeHeat = value;
    }

    /**
     * Gets the value of the garageSizeDd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGarageSizeDd() {
        return garageSizeDd;
    }

    /**
     * Sets the value of the garageSizeDd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGarageSizeDd(BigDecimal value) {
        this.garageSizeDd = value;
    }

    /**
     * Gets the value of the garageTypeDd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGarageTypeDd() {
        return garageTypeDd;
    }

    /**
     * Sets the value of the garageTypeDd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGarageTypeDd(BigDecimal value) {
        this.garageTypeDd = value;
    }

    /**
     * Gets the value of the heatTypeDd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHeatTypeDd() {
        return heatTypeDd;
    }

    /**
     * Sets the value of the heatTypeDd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHeatTypeDd(BigDecimal value) {
        this.heatTypeDd = value;
    }

    /**
     * Gets the value of the includetds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncludetds() {
        return includetds;
    }

    /**
     * Sets the value of the includetds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncludetds(String value) {
        this.includetds = value;
    }

    /**
     * Gets the value of the rentalIncome property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyType.RentalIncome }
     *     
     */
    public PropertyType.RentalIncome getRentalIncome() {
        return rentalIncome;
    }

    /**
     * Sets the value of the rentalIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyType.RentalIncome }
     *     
     */
    public void setRentalIncome(PropertyType.RentalIncome value) {
        this.rentalIncome = value;
    }

    /**
     * Gets the value of the insulatedWithUffi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsulatedWithUffi() {
        return insulatedWithUffi;
    }

    /**
     * Sets the value of the insulatedWithUffi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsulatedWithUffi(String value) {
        this.insulatedWithUffi = value;
    }

    /**
     * Gets the value of the legalLine1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalLine1() {
        return legalLine1;
    }

    /**
     * Sets the value of the legalLine1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalLine1(String value) {
        this.legalLine1 = value;
    }

    /**
     * Gets the value of the legalLine2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalLine2() {
        return legalLine2;
    }

    /**
     * Sets the value of the legalLine2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalLine2(String value) {
        this.legalLine2 = value;
    }

    /**
     * Gets the value of the legalLine3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalLine3() {
        return legalLine3;
    }

    /**
     * Sets the value of the legalLine3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalLine3(String value) {
        this.legalLine3 = value;
    }

    /**
     * Gets the value of the livingSpace property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLivingSpace() {
        return livingSpace;
    }

    /**
     * Sets the value of the livingSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLivingSpace(Integer value) {
        this.livingSpace = value;
    }

    /**
     * Gets the value of the livingSpaceUnitOfMeasurDd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLivingSpaceUnitOfMeasurDd() {
        return livingSpaceUnitOfMeasurDd;
    }

    /**
     * Sets the value of the livingSpaceUnitOfMeasurDd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLivingSpaceUnitOfMeasurDd(BigDecimal value) {
        this.livingSpaceUnitOfMeasurDd = value;
    }

    /**
     * Gets the value of the lotSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLotSize() {
        return lotSize;
    }

    /**
     * Sets the value of the lotSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLotSize(Integer value) {
        this.lotSize = value;
    }

    /**
     * Gets the value of the lotSizeUnitOfMeasureDd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLotSizeUnitOfMeasureDd() {
        return lotSizeUnitOfMeasureDd;
    }

    /**
     * Sets the value of the lotSizeUnitOfMeasureDd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLotSizeUnitOfMeasureDd(BigDecimal value) {
        this.lotSizeUnitOfMeasureDd = value;
    }

    /**
     * Gets the value of the mlsListingFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMlsListingFlag() {
        return mlsListingFlag;
    }

    /**
     * Sets the value of the mlsListingFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMlsListingFlag(String value) {
        this.mlsListingFlag = value;
    }

    /**
     * Gets the value of the newConstructionDd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNewConstructionDd() {
        return newConstructionDd;
    }

    /**
     * Sets the value of the newConstructionDd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNewConstructionDd(BigDecimal value) {
        this.newConstructionDd = value;
    }

    /**
     * Gets the value of the numberOfUnits property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumberOfUnits() {
        return numberOfUnits;
    }

    /**
     * Sets the value of the numberOfUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberOfUnits(Integer value) {
        this.numberOfUnits = value;
    }

    /**
     * Gets the value of the occupancyTypeDd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOccupancyTypeDd() {
        return occupancyTypeDd;
    }

    /**
     * Sets the value of the occupancyTypeDd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOccupancyTypeDd(BigDecimal value) {
        this.occupancyTypeDd = value;
    }

    /**
     * Gets the value of the originalPurchasePrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOriginalPurchasePrice() {
        return originalPurchasePrice;
    }

    /**
     * Sets the value of the originalPurchasePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOriginalPurchasePrice(BigDecimal value) {
        this.originalPurchasePrice = value;
    }

    /**
     * Gets the value of the propertyTypeDd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPropertyTypeDd() {
        return propertyTypeDd;
    }

    /**
     * Sets the value of the propertyTypeDd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPropertyTypeDd(BigDecimal value) {
        this.propertyTypeDd = value;
    }

    /**
     * Gets the value of the purchasePrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPurchasePrice() {
        return purchasePrice;
    }

    /**
     * Sets the value of the purchasePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPurchasePrice(BigDecimal value) {
        this.purchasePrice = value;
    }

    /**
     * Gets the value of the refiOrigPurchaseDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRefiOrigPurchaseDate() {
        return refiOrigPurchaseDate;
    }

    /**
     * Sets the value of the refiOrigPurchaseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRefiOrigPurchaseDate(XMLGregorianCalendar value) {
        this.refiOrigPurchaseDate = value;
    }

    /**
     * Gets the value of the sewageTypeDd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSewageTypeDd() {
        return sewageTypeDd;
    }

    /**
     * Sets the value of the sewageTypeDd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSewageTypeDd(BigDecimal value) {
        this.sewageTypeDd = value;
    }

    /**
     * Gets the value of the structureAge property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStructureAge() {
        return structureAge;
    }

    /**
     * Sets the value of the structureAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStructureAge(Integer value) {
        this.structureAge = value;
    }

    /**
     * Gets the value of the taxationYear property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTaxationYear() {
        return taxationYear;
    }

    /**
     * Sets the value of the taxationYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTaxationYear(Integer value) {
        this.taxationYear = value;
    }

    /**
     * Gets the value of the waterTypeDd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWaterTypeDd() {
        return waterTypeDd;
    }

    /**
     * Sets the value of the waterTypeDd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWaterTypeDd(BigDecimal value) {
        this.waterTypeDd = value;
    }

    /**
     * Gets the value of the propertyExpense property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the propertyExpense property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPropertyExpense().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PropertyType.PropertyExpense }
     * 
     * 
     */
    public List<PropertyType.PropertyExpense> getPropertyExpense() {
        if (propertyExpense == null) {
            propertyExpense = new ArrayList<PropertyType.PropertyExpense>();
        }
        return this.propertyExpense;
    }

    /**
     * Gets the value of the propertyadditionalData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the propertyadditionalData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPropertyadditionalData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdditionalDataType }
     * 
     * 
     */
    public List<AdditionalDataType> getPropertyadditionalData() {
        if (propertyadditionalData == null) {
            propertyadditionalData = new ArrayList<AdditionalDataType>();
        }
        return this.propertyadditionalData;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="propertyExpenseAmount">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *               &lt;totalDigits value="13"/>
     *               &lt;fractionDigits value="2"/>
     *               &lt;minExclusive value="-100000000000"/>
     *               &lt;maxExclusive value="100000000000"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="propertyExpenseDescription" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="80"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="propertyExpensePeriodDd">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *               &lt;totalDigits value="13"/>
     *               &lt;fractionDigits value="0"/>
     *               &lt;minExclusive value="-1"/>
     *               &lt;maxExclusive value="10000000000000"/>
     *               &lt;enumeration value="0"/>
     *               &lt;enumeration value="1"/>
     *               &lt;enumeration value="2"/>
     *               &lt;enumeration value="3"/>
     *               &lt;enumeration value="4"/>
     *               &lt;enumeration value="5"/>
     *               &lt;enumeration value="6"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="propertyExpenseTypeDd">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *               &lt;totalDigits value="13"/>
     *               &lt;fractionDigits value="0"/>
     *               &lt;minExclusive value="-1"/>
     *               &lt;maxExclusive value="10000000000000"/>
     *               &lt;enumeration value="0"/>
     *               &lt;enumeration value="1"/>
     *               &lt;enumeration value="2"/>
     *               &lt;enumeration value="3"/>
     *               &lt;enumeration value="4"/>
     *               &lt;enumeration value="5"/>
     *               &lt;enumeration value="6"/>
     *               &lt;enumeration value="7"/>
     *               &lt;enumeration value="8"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "propertyExpenseAmount",
        "propertyExpenseDescription",
        "propertyExpensePeriodDd",
        "propertyExpenseTypeDd"
    })
    public static class PropertyExpense {

        @XmlElement(required = true)
        protected BigDecimal propertyExpenseAmount;
        protected String propertyExpenseDescription;
        @XmlElement(required = true)
        protected BigDecimal propertyExpensePeriodDd;
        @XmlElement(required = true)
        protected BigDecimal propertyExpenseTypeDd;

        /**
         * Gets the value of the propertyExpenseAmount property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getPropertyExpenseAmount() {
            return propertyExpenseAmount;
        }

        /**
         * Sets the value of the propertyExpenseAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setPropertyExpenseAmount(BigDecimal value) {
            this.propertyExpenseAmount = value;
        }

        /**
         * Gets the value of the propertyExpenseDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPropertyExpenseDescription() {
            return propertyExpenseDescription;
        }

        /**
         * Sets the value of the propertyExpenseDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPropertyExpenseDescription(String value) {
            this.propertyExpenseDescription = value;
        }

        /**
         * Gets the value of the propertyExpensePeriodDd property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getPropertyExpensePeriodDd() {
            return propertyExpensePeriodDd;
        }

        /**
         * Sets the value of the propertyExpensePeriodDd property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setPropertyExpensePeriodDd(BigDecimal value) {
            this.propertyExpensePeriodDd = value;
        }

        /**
         * Gets the value of the propertyExpenseTypeDd property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getPropertyExpenseTypeDd() {
            return propertyExpenseTypeDd;
        }

        /**
         * Sets the value of the propertyExpenseTypeDd property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setPropertyExpenseTypeDd(BigDecimal value) {
            this.propertyExpenseTypeDd = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.filogix.com/Schema/FCXAPI/1}IncomeType">
     *       &lt;sequence>
     *         &lt;element name="incomeTypeDd" type="{http://www.filogix.com/Schema/FCXAPI/1}incomeTypeRentalDd"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "incomeTypeDd"
    })
    public static class RentalIncome
        extends IncomeType
    {

        @XmlElement(required = true)
        protected BigDecimal incomeTypeDd;

        /**
         * Gets the value of the incomeTypeDd property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getIncomeTypeDd() {
            return incomeTypeDd;
        }

        /**
         * Sets the value of the incomeTypeDd property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setIncomeTypeDd(BigDecimal value) {
            this.incomeTypeDd = value;
        }

    }

}
