//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.20 at 04:03:32 PM MST 
//


package com.syml.filogix;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReferralApplicationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReferralApplicationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="referredToAgent">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="firmCode">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="4"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="userLogin">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="12"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="referralUrl" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="deal" type="{http://www.filogix.com/Schema/FCXAPI/1}DealType"/>
 *         &lt;element name="applicantGroup" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="applicantGroupTypeDd">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                         &lt;totalDigits value="2"/>
 *                         &lt;fractionDigits value="0"/>
 *                         &lt;minExclusive value="-100"/>
 *                         &lt;maxExclusive value="100"/>
 *                         &lt;enumeration value="0"/>
 *                         &lt;enumeration value="1"/>
 *                         &lt;enumeration value="2"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="applicant" type="{http://www.filogix.com/Schema/FCXAPI/1}ApplicantApplicationType" maxOccurs="2"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="mortgage" type="{http://www.filogix.com/Schema/FCXAPI/1}MortgageType" maxOccurs="3" minOccurs="0"/>
 *         &lt;element name="subjectProperty" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="property" type="{http://www.filogix.com/Schema/FCXAPI/1}PropertyType" minOccurs="0"/>
 *                   &lt;element name="existingMortgage" type="{http://www.filogix.com/Schema/FCXAPI/1}MortgageType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="notes" type="{http://www.filogix.com/Schema/FCXAPI/1}DealNotesType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="additionalData" type="{http://www.filogix.com/Schema/FCXAPI/1}AdditionalDataType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReferralApplicationType", propOrder = {
    "referredToAgent",
    "referralUrl",
    "deal",
    "applicantGroup",
    "mortgage",
    "subjectProperty",
    "notes",
    "additionalData"
})
public class ReferralApplicationType {

    @XmlElement(required = true)
    protected ReferralApplicationType.ReferredToAgent referredToAgent;
    protected String referralUrl;
    @XmlElement(required = true)
    protected DealType deal;
    @XmlElement(required = true)
    protected List<ReferralApplicationType.ApplicantGroup> applicantGroup;
    protected List<MortgageType> mortgage;
    protected ReferralApplicationType.SubjectProperty subjectProperty;
    protected List<DealNotesType> notes;
    protected List<AdditionalDataType> additionalData;

    /**
     * Gets the value of the referredToAgent property.
     * 
     * @return
     *     possible object is
     *     {@link ReferralApplicationType.ReferredToAgent }
     *     
     */
    public ReferralApplicationType.ReferredToAgent getReferredToAgent() {
        return referredToAgent;
    }

    /**
     * Sets the value of the referredToAgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferralApplicationType.ReferredToAgent }
     *     
     */
    public void setReferredToAgent(ReferralApplicationType.ReferredToAgent value) {
        this.referredToAgent = value;
    }

    /**
     * Gets the value of the referralUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferralUrl() {
        return referralUrl;
    }

    /**
     * Sets the value of the referralUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferralUrl(String value) {
        this.referralUrl = value;
    }

    /**
     * Gets the value of the deal property.
     * 
     * @return
     *     possible object is
     *     {@link DealType }
     *     
     */
    public DealType getDeal() {
        return deal;
    }

    /**
     * Sets the value of the deal property.
     * 
     * @param value
     *     allowed object is
     *     {@link DealType }
     *     
     */
    public void setDeal(DealType value) {
        this.deal = value;
    }

    /**
     * Gets the value of the applicantGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the applicantGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApplicantGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReferralApplicationType.ApplicantGroup }
     * 
     * 
     */
    public List<ReferralApplicationType.ApplicantGroup> getApplicantGroup() {
        if (applicantGroup == null) {
            applicantGroup = new ArrayList<ReferralApplicationType.ApplicantGroup>();
        }
        return this.applicantGroup;
    }

    /**
     * Gets the value of the mortgage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mortgage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMortgage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MortgageType }
     * 
     * 
     */
    public List<MortgageType> getMortgage() {
        if (mortgage == null) {
            mortgage = new ArrayList<MortgageType>();
        }
        return this.mortgage;
    }

    /**
     * Gets the value of the subjectProperty property.
     * 
     * @return
     *     possible object is
     *     {@link ReferralApplicationType.SubjectProperty }
     *     
     */
    public ReferralApplicationType.SubjectProperty getSubjectProperty() {
        return subjectProperty;
    }

    /**
     * Sets the value of the subjectProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferralApplicationType.SubjectProperty }
     *     
     */
    public void setSubjectProperty(ReferralApplicationType.SubjectProperty value) {
        this.subjectProperty = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the notes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNotes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DealNotesType }
     * 
     * 
     */
    public List<DealNotesType> getNotes() {
        if (notes == null) {
            notes = new ArrayList<DealNotesType>();
        }
        return this.notes;
    }

    /**
     * Gets the value of the additionalData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdditionalDataType }
     * 
     * 
     */
    public List<AdditionalDataType> getAdditionalData() {
        if (additionalData == null) {
            additionalData = new ArrayList<AdditionalDataType>();
        }
        return this.additionalData;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="applicantGroupTypeDd">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *               &lt;totalDigits value="2"/>
     *               &lt;fractionDigits value="0"/>
     *               &lt;minExclusive value="-100"/>
     *               &lt;maxExclusive value="100"/>
     *               &lt;enumeration value="0"/>
     *               &lt;enumeration value="1"/>
     *               &lt;enumeration value="2"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="applicant" type="{http://www.filogix.com/Schema/FCXAPI/1}ApplicantApplicationType" maxOccurs="2"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "applicantGroupTypeDd",
        "applicant"
    })
    public static class ApplicantGroup {

        @XmlElement(required = true)
        protected BigDecimal applicantGroupTypeDd;
        @XmlElement(required = true)
        protected List<ApplicantApplicationType> applicant;

        /**
         * Gets the value of the applicantGroupTypeDd property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getApplicantGroupTypeDd() {
            return applicantGroupTypeDd;
        }

        /**
         * Sets the value of the applicantGroupTypeDd property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setApplicantGroupTypeDd(BigDecimal value) {
            this.applicantGroupTypeDd = value;
        }

        /**
         * Gets the value of the applicant property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the applicant property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getApplicant().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ApplicantApplicationType }
         * 
         * 
         */
        public List<ApplicantApplicationType> getApplicant() {
            if (applicant == null) {
                applicant = new ArrayList<ApplicantApplicationType>();
            }
            return this.applicant;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="firmCode">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="4"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="userLogin">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="12"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "firmCode",
        "userLogin"
    })
    public static class ReferredToAgent {

        @XmlElement(required = true)
        protected String firmCode;
        @XmlElement(required = true)
        protected String userLogin;

        /**
         * Gets the value of the firmCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFirmCode() {
            return firmCode;
        }

        /**
         * Sets the value of the firmCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFirmCode(String value) {
            this.firmCode = value;
        }

        /**
         * Gets the value of the userLogin property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUserLogin() {
            return userLogin;
        }

        /**
         * Sets the value of the userLogin property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUserLogin(String value) {
            this.userLogin = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="property" type="{http://www.filogix.com/Schema/FCXAPI/1}PropertyType" minOccurs="0"/>
     *         &lt;element name="existingMortgage" type="{http://www.filogix.com/Schema/FCXAPI/1}MortgageType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "property",
        "existingMortgage"
    })
    public static class SubjectProperty {

        protected PropertyType property;
        protected List<MortgageType> existingMortgage;

        /**
         * Gets the value of the property property.
         * 
         * @return
         *     possible object is
         *     {@link PropertyType }
         *     
         */
        public PropertyType getProperty() {
            return property;
        }

        /**
         * Sets the value of the property property.
         * 
         * @param value
         *     allowed object is
         *     {@link PropertyType }
         *     
         */
        public void setProperty(PropertyType value) {
            this.property = value;
        }

        /**
         * Gets the value of the existingMortgage property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the existingMortgage property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getExistingMortgage().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MortgageType }
         * 
         * 
         */
        public List<MortgageType> getExistingMortgage() {
            if (existingMortgage == null) {
                existingMortgage = new ArrayList<MortgageType>();
            }
            return this.existingMortgage;
        }

    }

}
