//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.20 at 04:03:32 PM MST 
//


package com.syml.filogix;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * User Profile
 * 
 * <p>Java class for UserProfileType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserProfileType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="contact" type="{http://www.filogix.com/Schema/FCXAPI/1}ContactTypeAddresstype1" minOccurs="0"/>
 *         &lt;element name="firmCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="legacyOfficeId" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="legacySystem" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="legacyUserId" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="licenseRegistrationNumber" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="profileStatusDd" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="2"/>
 *               &lt;fractionDigits value="0"/>
 *               &lt;minExclusive value="-100"/>
 *               &lt;maxExclusive value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="userProfileId">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="13"/>
 *               &lt;fractionDigits value="0"/>
 *               &lt;minExclusive value="-10000000000000"/>
 *               &lt;maxExclusive value="10000000000000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="userTypeDd" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="2"/>
 *               &lt;fractionDigits value="0"/>
 *               &lt;minExclusive value="-100"/>
 *               &lt;maxExclusive value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserProfileType", propOrder = {
    "contact",
    "firmCode",
    "legacyOfficeId",
    "legacySystem",
    "legacyUserId",
    "licenseRegistrationNumber",
    "profileStatusDd",
    "userProfileId",
    "userTypeDd"
})
public class UserProfileType {

    protected ContactTypeAddresstype1 contact;
    protected String firmCode;
    protected String legacyOfficeId;
    protected String legacySystem;
    protected String legacyUserId;
    protected String licenseRegistrationNumber;
    protected BigDecimal profileStatusDd;
    @XmlElement(required = true)
    protected BigDecimal userProfileId;
    protected BigDecimal userTypeDd;

    /**
     * Gets the value of the contact property.
     * 
     * @return
     *     possible object is
     *     {@link ContactTypeAddresstype1 }
     *     
     */
    public ContactTypeAddresstype1 getContact() {
        return contact;
    }

    /**
     * Sets the value of the contact property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactTypeAddresstype1 }
     *     
     */
    public void setContact(ContactTypeAddresstype1 value) {
        this.contact = value;
    }

    /**
     * Gets the value of the firmCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirmCode() {
        return firmCode;
    }

    /**
     * Sets the value of the firmCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirmCode(String value) {
        this.firmCode = value;
    }

    /**
     * Gets the value of the legacyOfficeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegacyOfficeId() {
        return legacyOfficeId;
    }

    /**
     * Sets the value of the legacyOfficeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegacyOfficeId(String value) {
        this.legacyOfficeId = value;
    }

    /**
     * Gets the value of the legacySystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegacySystem() {
        return legacySystem;
    }

    /**
     * Sets the value of the legacySystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegacySystem(String value) {
        this.legacySystem = value;
    }

    /**
     * Gets the value of the legacyUserId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegacyUserId() {
        return legacyUserId;
    }

    /**
     * Sets the value of the legacyUserId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegacyUserId(String value) {
        this.legacyUserId = value;
    }

    /**
     * Gets the value of the licenseRegistrationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicenseRegistrationNumber() {
        return licenseRegistrationNumber;
    }

    /**
     * Sets the value of the licenseRegistrationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicenseRegistrationNumber(String value) {
        this.licenseRegistrationNumber = value;
    }

    /**
     * Gets the value of the profileStatusDd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getProfileStatusDd() {
        return profileStatusDd;
    }

    /**
     * Sets the value of the profileStatusDd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setProfileStatusDd(BigDecimal value) {
        this.profileStatusDd = value;
    }

    /**
     * Gets the value of the userProfileId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUserProfileId() {
        return userProfileId;
    }

    /**
     * Sets the value of the userProfileId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUserProfileId(BigDecimal value) {
        this.userProfileId = value;
    }

    /**
     * Gets the value of the userTypeDd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUserTypeDd() {
        return userTypeDd;
    }

    /**
     * Sets the value of the userTypeDd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUserTypeDd(BigDecimal value) {
        this.userTypeDd = value;
    }

}
