<?php
define('THIS_IS_SOMEWHAT',__('This is somewhat embarrassing, isn&rsquo;t it?','black-rider'));
define('IT_SEEMS_WE',__('It seems we can&rsquo;t find what you&rsquo;re looking for. Perhaps searching, or one of the links below, can help.', 'black-rider'));
define('MOST_USED_CATEGORIES',__('Most Used Categories', 'black-rider'));
define('MONTHLY_ARCHIVES',__('Try looking in the monthly archives. %1$s', 'black-rider'));
define('SORRY_NO_POST_MATCHED',__('Sorry, no posts matched your criteria.', 'black-rider'));
define('NOTHING_FOUND',__('Nothing Found here', 'black-rider'));
define('NOTHING_MATCHED',__('Sorry, but nothing matched your search criteria. Please try again with some diffrent keyword', 'black-rider'));
define('CATEGORIES',__('Categories', 'black-rider'));
define('ARCHIVES',__('Archives', 'black-rider'));
define('BLOG_ARCHIVES',__('Blog Archives', 'black-rider'));
define('CATEGORY_ARCHIVES',__('Category Archives: %s', 'black-rider'));
define('PAGE',__('Page %s', 'black-rider'));
define('SEARCH_RESULT',__('Search Results for: %s', 'black-rider'));
define('TAG_ARCHIVES',__('Tag Archives: %s', 'black-rider'));
define('DAILY_ARCHIVES',__('Daily Archives: %s', 'black-rider'));
define('MONTHLY_ARCHIVESS',__('Monthly Archives: %s', 'black-rider'));
define('YEARLY_ARCHIVES',__('Yearly Archives: %s', 'black-rider'));
define('AUTHOR_ARCHIVES',__('Author Archives: %s', 'black-rider'));
define('ABOUT',__('About: %s', 'black-rider'));
define('HOME_TEXT',__('Home', 'black-rider'));
define('POSTED_ENTRY',__('This entry was posted in %1$s and tagged %2$s. Bookmark the <a href="%3$s" title="Permalink to %4$s" rel="bookmark">permalink</a>.', 'black-rider'));
define('POSTED_BOOKMARK',__('This entry was posted in %1$s. Bookmark the <a href="%3$s" title="Permalink to %4$s" rel="bookmark">permalink</a>.', 'black-rider'));
define('BOOKMARK',__('Bookmark the <a href="%3$s" title="Permalink to %4$s" rel="bookmark">permalink</a>.', 'black-rider'));
define('PRIMARY_WIDGET',__('Primary Widget Area', 'black-rider'));
define('THE_PRIMARY_WIDGET',__('The primary widget area', 'black-rider'));
define('SECONDRY_WIDGET',__('Secondary Widget Area', 'black-rider'));
define('THE_SECONDRY_WIDGET',__('The secondary widget area', 'black-rider'));
define('RIGHT_WIDGET',__('Home Page Right Feature Widget Area', 'black-rider'));
define('THE_RIGHT_WIDGET',__('The Home Page Right Feature widget area', 'black-rider'));
define('FIRST_FOOTER_WIDGET',__('First Footer Widget Area', 'black-rider'));
define('THE_FIRST_FOOTER_WIDGET',__('The first footer widget area', 'black-rider'));
define('SECONDRY_FOOTER_WIDGET',__('Second Footer Widget Area', 'black-rider'));
define('THE_SECONDRY_FOOTER_WIDGET',__('The second footer widget area', 'black-rider'));
define('THIRD_FOOTER_WIDGET',__('Third Footer Widget Area', 'black-rider'));
define('THE_THIRD_FOOTER_WIDGET',__('The third footer widget area', 'black-rider'));
define('FOURTH_FOOTER_WIDGET',__('Fourth Footer Widget Area', 'black-rider'));
define('THE_FOURTH_FOOTER_WIDGET',__('The fourth footer widget area', 'black-rider'));
define('OLDER_POSTS',__('&larr; Older posts', 'black-rider'));
define('NEWER_POSTS',__('Newer posts &rarr;', 'black-rider'));
define('PREV_POST',__('&larr; Previous Post', 'black-rider'));
define('NEXT_POST',__('Next Post &rarr;', 'black-rider'));
define('READ_MORE',__('Read More', 'black-rider'));
define('SND_MSG',__('Send Your Message', 'black-rider'));
?>