//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.23 at 03:36:43 PM MDT 
//


package com.syml.morweb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="earnedIncomeType" use="required" type="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typeEarnedIncomeType" />
 *       &lt;attribute name="paymentFrequency" use="required" type="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typePaymentFrequency" />
 *       &lt;attribute name="earnedIncomeAmount" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;minExclusive value="0"/>
 *             &lt;fractionDigits value="2"/>
 *             &lt;totalDigits value="9"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "EarnedIncome")
public class EarnedIncome {

    @XmlAttribute(name = "earnedIncomeType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String earnedIncomeType;
    @XmlAttribute(name = "paymentFrequency", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String paymentFrequency;
    @XmlAttribute(name = "earnedIncomeAmount", required = true)
    protected BigDecimal earnedIncomeAmount;

    /**
     * Gets the value of the earnedIncomeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEarnedIncomeType() {
        return earnedIncomeType;
    }

    /**
     * Sets the value of the earnedIncomeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEarnedIncomeType(String value) {
        this.earnedIncomeType = value;
    }

    /**
     * Gets the value of the paymentFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentFrequency() {
        return paymentFrequency;
    }

    /**
     * Sets the value of the paymentFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentFrequency(String value) {
        this.paymentFrequency = value;
    }

    /**
     * Gets the value of the earnedIncomeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEarnedIncomeAmount() {
        return earnedIncomeAmount;
    }

    /**
     * Sets the value of the earnedIncomeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEarnedIncomeAmount(BigDecimal value) {
        this.earnedIncomeAmount = value;
    }

}
