//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.17 at 04:35:20 AM ICT 
//


package com.syml.morweb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}SubjectPropertyList" minOccurs="0"/>
 *         &lt;element ref="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}ApplicationNoteList" minOccurs="0"/>
 *         &lt;element ref="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}LoanList" minOccurs="0"/>
 *         &lt;element ref="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}DownpaymentList" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="isPreapproval" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="fundingDate" type="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typeDate" />
 *       &lt;attribute name="loanPurposeType" type="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typeLoanPurposeType" />
 *       &lt;attribute name="purchasePriceEstimatedValue" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="brokerUserId" type="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typeUserId" />
 *       &lt;attribute name="agentUserId" type="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typeUserId" />
 *       &lt;attribute name="adminUserId" type="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typeUserId" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "subjectPropertyList",
    "applicationNoteList",
    "loanList",
    "downpaymentList"
})
@XmlRootElement(name = "MortgageApplication", namespace="http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1")
public class MortgageApplication {

    @XmlElement(name = "SubjectPropertyList")
    protected SubjectPropertyList subjectPropertyList;
    @XmlElement(name = "ApplicationNoteList")
    protected ApplicationNoteList applicationNoteList;
    @XmlElement(name = "LoanList")
    protected LoanList loanList;
    @XmlElement(name = "DownpaymentList")
    protected DownpaymentList downpaymentList;
    @XmlAttribute(name = "isPreapproval")
    protected Boolean isPreapproval;
    @XmlAttribute(name = "fundingDate")
    protected XMLGregorianCalendar fundingDate;
    @XmlAttribute(name = "loanPurposeType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String loanPurposeType;
    @XmlAttribute(name = "purchasePriceEstimatedValue")
    protected Float purchasePriceEstimatedValue;
    @XmlAttribute(name = "brokerUserId")
    protected String brokerUserId;
    @XmlAttribute(name = "agentUserId")
    protected String agentUserId;
    @XmlAttribute(name = "adminUserId")
    protected String adminUserId;

    /**
     * Currently only 1 subject property can be included for MorWEB applications. If there are multiple securing properties, enter the primary property within the SubjectPropertyList and create one or more Application notes to contain the details of the other properties.
     * 
     * @return
     *     possible object is
     *     {@link SubjectPropertyList }
     *     
     */
    public SubjectPropertyList getSubjectPropertyList() {
        return subjectPropertyList;
    }

    /**
     * Sets the value of the subjectPropertyList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubjectPropertyList }
     *     
     */
    public void setSubjectPropertyList(SubjectPropertyList value) {
        this.subjectPropertyList = value;
    }

    /**
     * Notes to be attached to the Application. Will show within MemoPad on Morweb
     * 
     * @return
     *     possible object is
     *     {@link ApplicationNoteList }
     *     
     */
    public ApplicationNoteList getApplicationNoteList() {
        return applicationNoteList;
    }

    /**
     * Sets the value of the applicationNoteList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationNoteList }
     *     
     */
    public void setApplicationNoteList(ApplicationNoteList value) {
        this.applicationNoteList = value;
    }

    /**
     * Currently only 1 mortgage loan can be ingested via MorWEB BDI (Broker Data Ingestion).
     * 
     * @return
     *     possible object is
     *     {@link LoanList }
     *     
     */
    public LoanList getLoanList() {
        return loanList;
    }

    /**
     * Sets the value of the loanList property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoanList }
     *     
     */
    public void setLoanList(LoanList value) {
        this.loanList = value;
    }

    /**
     * Gets the value of the downpaymentList property.
     * 
     * @return
     *     possible object is
     *     {@link DownpaymentList }
     *     
     */
    public DownpaymentList getDownpaymentList() {
        return downpaymentList;
    }

    /**
     * Sets the value of the downpaymentList property.
     * 
     * @param value
     *     allowed object is
     *     {@link DownpaymentList }
     *     
     */
    public void setDownpaymentList(DownpaymentList value) {
        this.downpaymentList = value;
    }

    /**
     * Gets the value of the isPreapproval property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsPreapproval() {
        return isPreapproval;
    }

    /**
     * Sets the value of the isPreapproval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPreapproval(Boolean value) {
        this.isPreapproval = value;
    }

    /**
     * Gets the value of the fundingDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFundingDate() {
        return fundingDate;
    }

    /**
     * Sets the value of the fundingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFundingDate(XMLGregorianCalendar value) {
        this.fundingDate = value;
    }

    /**
     * Gets the value of the loanPurposeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoanPurposeType() {
        return loanPurposeType;
    }

    /**
     * Sets the value of the loanPurposeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoanPurposeType(String value) {
        this.loanPurposeType = value;
    }

    /**
     * Gets the value of the purchasePriceEstimatedValue property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getPurchasePriceEstimatedValue() {
        return purchasePriceEstimatedValue;
    }

    /**
     * Sets the value of the purchasePriceEstimatedValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setPurchasePriceEstimatedValue(Float value) {
        this.purchasePriceEstimatedValue = value;
    }

    /**
     * Gets the value of the brokerUserId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrokerUserId() {
        return brokerUserId;
    }

    /**
     * Sets the value of the brokerUserId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrokerUserId(String value) {
        this.brokerUserId = value;
    }

    /**
     * Gets the value of the agentUserId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgentUserId() {
        return agentUserId;
    }

    /**
     * Sets the value of the agentUserId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgentUserId(String value) {
        this.agentUserId = value;
    }

    /**
     * Gets the value of the adminUserId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdminUserId() {
        return adminUserId;
    }

    /**
     * Sets the value of the adminUserId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdminUserId(String value) {
        this.adminUserId = value;
    }

}
