//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.03 at 12:30:42 AM ICT 
//


package com.syml.morweb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import com.syml.domain.Applicant;
import com.syml.domain.Asset;
import com.syml.domain.Property;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.syml.mscbdi package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ApplicationAddress_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "ApplicationAddress");
    private final static QName _CreditReport_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "CreditReport");
    private final static QName _CustomerAddressCorrespondence_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "CustomerAddressCorrespondence");
    private final static QName _ApplicationAddressOther_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "ApplicationAddressOther");
    private final static QName _ApplicationAddressCanada_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "ApplicationAddressCanada");
    private final static QName _CustomerAddressSecondaryResidence_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "CustomerAddressSecondaryResidence");
    private final static QName _CustomerAddressPreviousResidence_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "CustomerAddressPreviousResidence");
    private final static QName _CustomerAddressInvestmentProperty_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "CustomerAddressInvestmentProperty");
    private final static QName _AddressOccupancyOwnerOccupied_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "AddressOccupancyOwnerOccupied");
    private final static QName _Asset_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "Asset");
    private final static QName _AddressOther_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "AddressOther");
    private final static QName _AddressOccupancyTenant_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "AddressOccupancyTenant");
    private final static QName _CustomerAddress_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "CustomerAddress");
    private final static QName _MunicipalAddressUSA_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "MunicipalAddressUSA");
    private final static QName _CustomerAddressPrimaryResidence_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "CustomerAddressPrimaryResidence");
    private final static QName _CustomerBorrower_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "CustomerBorrower");
    private final static QName _AddressUSA_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "AddressUSA");
    private final static QName _PostalAddress_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "PostalAddress");
    private final static QName _AddressOccupancy_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "AddressOccupancy");
    private final static QName _AssetOther_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "AssetOther");
    private final static QName _CreditReportEquifax_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "CreditReportEquifax");
    private final static QName _MunicipalAddressOther_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "MunicipalAddressOther");
    private final static QName _AddressOccupancyNone_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "AddressOccupancyNone");
    private final static QName _CustomerAddressVacationProperty_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "CustomerAddressVacationProperty");
    private final static QName _Liability_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "Liability");
    private final static QName _PostalAddressPOBox_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "PostalAddressPOBox");
    private final static QName _Customer_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "Customer");
    private final static QName _CreditBureau_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "CreditBureau");
    private final static QName _ApplicationAddressUSA_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "ApplicationAddressUSA");
    private final static QName _LiabilityOther_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "LiabilityOther");
    private final static QName _CustomerAddressList_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "CustomerAddressList");
    private final static QName _CustomerReference_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "CustomerReference");
    private final static QName _AddressCanada_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "AddressCanada");
    private final static QName _MunicipalAddress_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "MunicipalAddress");
    private final static QName _CustomerGuarantor_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "CustomerGuarantor");
    private final static QName _AddressOccupancyRental_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "AddressOccupancyRental");
    private final static QName _PostalAddressStreetAddress_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "PostalAddressStreetAddress");
    private final static QName _AssetRealEstate_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "AssetRealEstate");
    private final static QName _AddressOccupancyPartialOwnerOccupied_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "AddressOccupancyPartialOwnerOccupied");
    private final static QName _LiabilityRealEstate_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "LiabilityRealEstate");
    private final static QName _MunicipalAddressCanada_QNAME = new QName("http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", "MunicipalAddressCanada");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.syml.mscbdi
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SubjectPropertyList }
     * 
     */
    public SubjectPropertyList createSubjectPropertyList() {
        return new SubjectPropertyList();
    }

    /**
     * Create an instance of {@link SubjectProperty }
     * 
     */
    public SubjectProperty createSubjectProperty() {
        return new SubjectProperty();
    }

    /**
     * Create an instance of {@link SubjectPropertyOccupancyOwnerOccupied }
     * 
     */
    public SubjectPropertyOccupancyOwnerOccupied createSubjectPropertyOccupancyOwnerOccupied() {
        return new SubjectPropertyOccupancyOwnerOccupied();
    }

    /**
     * Create an instance of {@link SubjectPropertyOccupancyPartialOwnerOccupied }
     * 
     */
    public SubjectPropertyOccupancyPartialOwnerOccupied createSubjectPropertyOccupancyPartialOwnerOccupied() {
        return new SubjectPropertyOccupancyPartialOwnerOccupied();
    }

    /**
     * Create an instance of {@link RentalDetails }
     * 
     */
    public RentalDetails createRentalDetails() {
        return new RentalDetails();
    }

    /**
     * Create an instance of {@link SubjectPropertyOccupancyRental }
     * 
     */
    public SubjectPropertyOccupancyRental createSubjectPropertyOccupancyRental() {
        return new SubjectPropertyOccupancyRental();
    }

    /**
     * Create an instance of {@link LegalAddress }
     * 
     */
    public LegalAddress createLegalAddress() {
        return new LegalAddress();
    }

    /**
     * Create an instance of {@link Freehold }
     * 
     */
    public Freehold createFreehold() {
        return new Freehold();
    }

    /**
     * Create an instance of {@link Leasehold }
     * 
     */
    public Leasehold createLeasehold() {
        return new Leasehold();
    }

    /**
     * Create an instance of {@link Condo }
     * 
     */
    public Condo createCondo() {
        return new Condo();
    }

    /**
     * Create an instance of {@link PropertyTax }
     * 
     */
    public PropertyTax createPropertyTax() {
        return new PropertyTax();
    }

    /**
     * Create an instance of {@link PropertyAppraisal }
     * 
     */
    public PropertyAppraisal createPropertyAppraisal() {
        return new PropertyAppraisal();
    }

    /**
     * Create an instance of {@link SubjectPropertyAddress }
     * 
     */
    public SubjectPropertyAddress createSubjectPropertyAddress() {
        return new SubjectPropertyAddress();
    }

    /**
     * Create an instance of {@link ApplicationNote }
     * 
     */
    public ApplicationNote createApplicationNote() {
        return new ApplicationNote();
    }

    /**
     * Create an instance of {@link CustomerAddressCorrespondence }
     * 
     */
    public CustomerAddressCorrespondence createCustomerAddressCorrespondence() {
        return new CustomerAddressCorrespondence();
    }

    /**
     * Create an instance of {@link TypeCreditReport }
     * 
     */
    public TypeCreditReport createTypeCreditReport() {
        return new TypeCreditReport();
    }

    /**
     * Create an instance of {@link MortgageApplication }
     * 
     */
    public MortgageApplication createMortgageApplication() {
        return new MortgageApplication();
    }

    /**
     * Create an instance of {@link ApplicationNoteList }
     * 
     */
    public ApplicationNoteList createApplicationNoteList() {
        return new ApplicationNoteList();
    }

    /**
     * Create an instance of {@link LoanList }
     * 
     */
    public LoanList createLoanList() {
        return new LoanList();
    }

    /**
     * Create an instance of {@link Loan }
     * 
     */
    public Loan createLoan() {
        return new Loan();
    }

    /**
     * Create an instance of {@link DownpaymentList }
     * 
     */
    public DownpaymentList createDownpaymentList() {
        return new DownpaymentList();
    }

    /**
     * Create an instance of {@link Downpayment }
     * 
     */
    public Downpayment createDownpayment() {
        return new Downpayment();
    }

    /**
     * Create an instance of {@link CustomerLiabilityList }
     * 
     */
    public CustomerLiabilityList createCustomerLiabilityList() {
        return new CustomerLiabilityList();
    }

    /**
     * Create an instance of {@link CustomerLiabilityOther }
     * 
     */
    public CustomerLiabilityOther createCustomerLiabilityOther() {
        return new CustomerLiabilityOther();
    }

    /**
     * Create an instance of {@link TypeCustomerReference }
     * 
     */
    public TypeCustomerReference createTypeCustomerReference() {
        return new TypeCustomerReference();
    }

    /**
     * Create an instance of {@link UnearnedIncome }
     * 
     */
    public UnearnedIncome createUnearnedIncome() {
        return new UnearnedIncome();
    }

    /**
     * Create an instance of {@link TypeApplicationAddressOther }
     * 
     */
    public TypeApplicationAddressOther createTypeApplicationAddressOther() {
        return new TypeApplicationAddressOther();
    }

    /**
     * Create an instance of {@link TypeApplicationAddress }
     * 
     */
    public TypeApplicationAddress createTypeApplicationAddress() {
        return new TypeApplicationAddress();
    }

    /**
     * Create an instance of {@link BDIRequest }
     * 
     */
    public BDIRequest createBDIRequest() {
        return new BDIRequest();
    }

    /**
     * Create an instance of {@link CommonData }
     * 
     */
    public CommonData createCommonData() {
        return new CommonData();
    }

    /**
     * Create an instance of {@link AssetList }
     * 
     */
    public AssetList createAssetList() {
        return new AssetList();
    }

    /**
     * Create an instance of {@link LiabilityList }
     * 
     */
    public LiabilityList createLiabilityList() {
        return new LiabilityList();
    }

    /**
     * Create an instance of {@link TypeLiability }
     * 
     */
    public TypeLiability createTypeLiability() {
        return new TypeLiability();
    }

    /**
     * Create an instance of {@link AddressList }
     * 
     */
    public AddressList createAddressList() {
        return new AddressList();
    }

    /**
     * Create an instance of {@link CreditBureauList }
     * 
     */
    public CreditBureauList createCreditBureauList() {
        return new CreditBureauList();
    }

    /**
     * Create an instance of {@link TypeCreditBureau }
     * 
     */
    public TypeCreditBureau createTypeCreditBureau() {
        return new TypeCreditBureau();
    }

    /**
     * Create an instance of {@link CustomerData }
     * 
     */
    public CustomerData createCustomerData() {
        return new CustomerData();
    }

    /**
     * Create an instance of {@link CustomerList }
     * 
     */
    public CustomerList createCustomerList() {
        return new CustomerList();
    }

    /**
     * Create an instance of {@link TypeCustomer }
     * 
     */
    public TypeCustomer createTypeCustomer() {
        return new TypeCustomer();
    }

    /*public TypeCustomer createTypeCustomer(Applicant applicant) {
    	return new TypeCustomer(applicant);
    }*/

    /**
     * Create an instance of {@link TypeCustomerAddressList }
     * 
     */
    public TypeCustomerAddressList createTypeCustomerAddressList() {
        return new TypeCustomerAddressList();
    }

    /**
     * Create an instance of {@link CustomerAssetList }
     * 
     */
    public CustomerAssetList createCustomerAssetList() {
        return new CustomerAssetList();
    }

    /**
     * Create an instance of {@link CustomerAssetOther }
     * 
     */
    public CustomerAssetOther createCustomerAssetOther() {
        return new CustomerAssetOther();
    }

    /**
     * Create an instance of {@link CustomerCreditBureauList }
     * 
     */
    public CustomerCreditBureauList createCustomerCreditBureauList() {
        return new CustomerCreditBureauList();
    }

    /**
     * Create an instance of {@link CustomerCreditBureau }
     * 
     */
    public CustomerCreditBureau createCustomerCreditBureau() {
        return new CustomerCreditBureau();
    }

    /**
     * Create an instance of {@link TypeAddressOccupancyTenant }
     * 
     */
    public TypeAddressOccupancyTenant createTypeAddressOccupancyTenant() {
        return new TypeAddressOccupancyTenant();
    }

    /**
     * Create an instance of {@link TelephoneNumber }
     * 
     */
    public TelephoneNumber createTelephoneNumber() {
        return new TelephoneNumber();
    }

    /**
     * Create an instance of {@link CustomerAddressSecondaryResidence }
     * 
     */
    public CustomerAddressSecondaryResidence createCustomerAddressSecondaryResidence() {
        return new CustomerAddressSecondaryResidence();
    }

    /**
     * Create an instance of {@link EarnedIncome }
     * 
     */
    public EarnedIncome createEarnedIncome() {
        return new EarnedIncome();
    }

    /**
     * Create an instance of {@link UnearnedIncomeList }
     * 
     */
    public UnearnedIncomeList createUnearnedIncomeList() {
        return new UnearnedIncomeList();
    }

    /**
     * Create an instance of {@link TypeApplicationAddressUSA }
     * 
     */
    public TypeApplicationAddressUSA createTypeApplicationAddressUSA() {
        return new TypeApplicationAddressUSA();
    }

    /**
     * Create an instance of {@link TypeCreditReportEquifax }
     * 
     */
    public TypeCreditReportEquifax createTypeCreditReportEquifax() {
        return new TypeCreditReportEquifax();
    }

    /**
     * Create an instance of {@link TypeAssetOther }
     * 
     */
    public TypeAssetOther createTypeAssetOther() {
        return new TypeAssetOther();
    }
    
    public TypeAssetOther createTypeAssetOther(int key, Asset symlAsset, Applicant applicant) {
        return new TypeAssetOther(key, symlAsset, applicant);
    }
    
    public TypeAssetOther createTypeAssetOther(int key, Property symlProperty, Applicant applicant) {
        return new TypeAssetOther(key, symlProperty, applicant);
    }

    /**
     * Create an instance of {@link BankruptcyHistory }
     * 
     */
    public BankruptcyHistory createBankruptcyHistory() {
        return new BankruptcyHistory();
    }

    /**
     * Create an instance of {@link BankruptcyHistoryList }
     * 
     */
    public BankruptcyHistoryList createBankruptcyHistoryList() {
        return new BankruptcyHistoryList();
    }

    /**
     * Create an instance of {@link TypeAddressOccupancyNone }
     * 
     */
    public TypeAddressOccupancyNone createTypeAddressOccupancyNone() {
        return new TypeAddressOccupancyNone();
    }

    /**
     * Create an instance of {@link CustomerAddressVacationProperty }
     * 
     */
    public CustomerAddressVacationProperty createCustomerAddressVacationProperty() {
        return new CustomerAddressVacationProperty();
    }

    /**
     * Create an instance of {@link TypeLiabilityRealEstate }
     * 
     */
    public TypeLiabilityRealEstate createTypeLiabilityRealEstate() {
        return new TypeLiabilityRealEstate();
    }

    /**
     * Create an instance of {@link EmploymentList }
     * 
     */
    public EmploymentList createEmploymentList() {
        return new EmploymentList();
    }

    /**
     * Create an instance of {@link Employment }
     * 
     */
    public Employment createEmployment() {
        return new Employment();
    }

    /**
     * Create an instance of {@link TypeAddressCanada }
     * 
     */
    public TypeAddressCanada createTypeAddressCanada() {
        return new TypeAddressCanada();
    }

    /**
     * Create an instance of {@link TypeAddressUSA }
     * 
     */
    public TypeAddressUSA createTypeAddressUSA() {
        return new TypeAddressUSA();
    }

    /**
     * Create an instance of {@link TypeAddressOther }
     * 
     */
    public TypeAddressOther createTypeAddressOther() {
        return new TypeAddressOther();
    }

    /**
     * Create an instance of {@link EarnedIncomeList }
     * 
     */
    public EarnedIncomeList createEarnedIncomeList() {
        return new EarnedIncomeList();
    }

    /**
     * Create an instance of {@link ContactTelephoneNumber }
     * 
     */
    public ContactTelephoneNumber createContactTelephoneNumber() {
        return new ContactTelephoneNumber();
    }

    /**
     * Create an instance of {@link CustomerNoteList }
     * 
     */
    public CustomerNoteList createCustomerNoteList() {
        return new CustomerNoteList();
    }

    /**
     * Create an instance of {@link CustomerNote }
     * 
     */
    public CustomerNote createCustomerNote() {
        return new CustomerNote();
    }

    /**
     * Create an instance of {@link TypeAddressOccupancyPartialOwnerOccupied }
     * 
     */
    public TypeAddressOccupancyPartialOwnerOccupied createTypeAddressOccupancyPartialOwnerOccupied() {
        return new TypeAddressOccupancyPartialOwnerOccupied();
    }

    /**
     * Create an instance of {@link CustomerLiabilityRealEstate }
     * 
     */
    public CustomerLiabilityRealEstate createCustomerLiabilityRealEstate() {
        return new CustomerLiabilityRealEstate();
    }

    /**
     * Create an instance of {@link TypeAssetRealEstate }
     * 
     */
    public TypeAssetRealEstate createTypeAssetRealEstate() {
        return new TypeAssetRealEstate();
    }

    /**
     * Create an instance of {@link TypeAddressOccupancyRental }
     * 
     */
    public TypeAddressOccupancyRental createTypeAddressOccupancyRental() {
        return new TypeAddressOccupancyRental();
    }

    /**
     * Create an instance of {@link CustomerTelephoneNumber }
     * 
     */
    public CustomerTelephoneNumber createCustomerTelephoneNumber() {
        return new CustomerTelephoneNumber();
    }

    /**
     * Create an instance of {@link CustomerTelephoneNumber }
     * 
     */
    public CustomerTelephoneNumber createCustomerTelephoneNumber(final String numberAsString) {
        return new CustomerTelephoneNumber(numberAsString);
    }

    /**
     * Create an instance of {@link CustomerTelephoneNumber }
     * 
     */
    public CustomerTelephoneNumber createCustomerTelephoneNumber(final String numberAsString, final boolean preferred) {
        final CustomerTelephoneNumber customerTelephoneNumber = new CustomerTelephoneNumber(numberAsString);
        customerTelephoneNumber.setPreferred(preferred);
        return customerTelephoneNumber;
    }

    /**
     * Create an instance of {@link TypeApplicationAddressCanada }
     * 
     */
    public TypeApplicationAddressCanada createTypeApplicationAddressCanada() {
        return new TypeApplicationAddressCanada();
    }

    /**
     * Create an instance of {@link CustomerAddressPrimaryResidence }
     * 
     */
    public CustomerAddressPrimaryResidence createCustomerAddressPrimaryResidence() {
        return new CustomerAddressPrimaryResidence();
    }

    /**
     * Create an instance of {@link TypeMunicipalAddressUSA }
     * 
     */
    public TypeMunicipalAddressUSA createTypeMunicipalAddressUSA() {
        return new TypeMunicipalAddressUSA();
    }

    /**
     * Create an instance of {@link TypeAddressOccupancyOwnerOccupied }
     * 
     */
    public TypeAddressOccupancyOwnerOccupied createTypeAddressOccupancyOwnerOccupied() {
        return new TypeAddressOccupancyOwnerOccupied();
    }

    /**
     * Create an instance of {@link CustomerAddressInvestmentProperty }
     * 
     */
    public CustomerAddressInvestmentProperty createCustomerAddressInvestmentProperty() {
        return new CustomerAddressInvestmentProperty();
    }

    /**
     * Create an instance of {@link CustomerAddressPreviousResidence }
     * 
     */
    public CustomerAddressPreviousResidence createCustomerAddressPreviousResidence() {
        return new CustomerAddressPreviousResidence();
    }

    /**
     * Create an instance of {@link CustomerTelephoneNumberList }
     * 
     */
    public CustomerTelephoneNumberList createCustomerTelephoneNumberList() {
        return new CustomerTelephoneNumberList();
    }

    /**
     * Create an instance of {@link TypePostalAddressPOBox }
     * 
     */
    public TypePostalAddressPOBox createTypePostalAddressPOBox() {
        return new TypePostalAddressPOBox();
    }

    /**
     * Create an instance of {@link TypeLiabilityOther }
     * 
     */
    public TypeLiabilityOther createTypeLiabilityOther() {
        return new TypeLiabilityOther();
    }

    /**
     * Create an instance of {@link TypeMunicipalAddressOther }
     * 
     */
    public TypeMunicipalAddressOther createTypeMunicipalAddressOther() {
        return new TypeMunicipalAddressOther();
    }

    /**
     * Create an instance of {@link TypeMunicipalAddressCanada }
     * 
     */
    public TypeMunicipalAddressCanada createTypeMunicipalAddressCanada() {
        return new TypeMunicipalAddressCanada();
    }

    /**
     * Create an instance of {@link TypePostalAddressStreetAddress }
     * 
     */
    public TypePostalAddressStreetAddress createTypePostalAddressStreetAddress() {
        return new TypePostalAddressStreetAddress();
    }

    /**
     * Create an instance of {@link TypeAssetList }
     * 
     */
    public TypeAssetList createTypeAssetList() {
        return new TypeAssetList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeApplicationAddress }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "ApplicationAddress")
    public JAXBElement<TypeApplicationAddress> createApplicationAddress(TypeApplicationAddress value) {
        return new JAXBElement<TypeApplicationAddress>(_ApplicationAddress_QNAME, TypeApplicationAddress.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeCreditReport }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "CreditReport")
    public JAXBElement<TypeCreditReport> createCreditReport(TypeCreditReport value) {
        return new JAXBElement<TypeCreditReport>(_CreditReport_QNAME, TypeCreditReport.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomerAddressCorrespondence }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "CustomerAddressCorrespondence", substitutionHeadNamespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", substitutionHeadName = "CustomerAddress")
    public JAXBElement<CustomerAddressCorrespondence> createCustomerAddressCorrespondence(CustomerAddressCorrespondence value) {
        return new JAXBElement<CustomerAddressCorrespondence>(_CustomerAddressCorrespondence_QNAME, CustomerAddressCorrespondence.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeApplicationAddressOther }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "ApplicationAddressOther", substitutionHeadNamespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", substitutionHeadName = "ApplicationAddress")
    public JAXBElement<TypeApplicationAddressOther> createApplicationAddressOther(TypeApplicationAddressOther value) {
        return new JAXBElement<TypeApplicationAddressOther>(_ApplicationAddressOther_QNAME, TypeApplicationAddressOther.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeApplicationAddressCanada }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "ApplicationAddressCanada", substitutionHeadNamespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", substitutionHeadName = "ApplicationAddress")
    public JAXBElement<TypeApplicationAddressCanada> createApplicationAddressCanada(TypeApplicationAddressCanada value) {
        return new JAXBElement<TypeApplicationAddressCanada>(_ApplicationAddressCanada_QNAME, TypeApplicationAddressCanada.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomerAddressSecondaryResidence }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "CustomerAddressSecondaryResidence", substitutionHeadNamespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", substitutionHeadName = "CustomerAddress")
    public JAXBElement<CustomerAddressSecondaryResidence> createCustomerAddressSecondaryResidence(CustomerAddressSecondaryResidence value) {
        return new JAXBElement<CustomerAddressSecondaryResidence>(_CustomerAddressSecondaryResidence_QNAME, CustomerAddressSecondaryResidence.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomerAddressPreviousResidence }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "CustomerAddressPreviousResidence", substitutionHeadNamespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", substitutionHeadName = "CustomerAddress")
    public JAXBElement<CustomerAddressPreviousResidence> createCustomerAddressPreviousResidence(CustomerAddressPreviousResidence value) {
        return new JAXBElement<CustomerAddressPreviousResidence>(_CustomerAddressPreviousResidence_QNAME, CustomerAddressPreviousResidence.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomerAddressInvestmentProperty }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "CustomerAddressInvestmentProperty", substitutionHeadNamespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", substitutionHeadName = "CustomerAddress")
    public JAXBElement<CustomerAddressInvestmentProperty> createCustomerAddressInvestmentProperty(CustomerAddressInvestmentProperty value) {
        return new JAXBElement<CustomerAddressInvestmentProperty>(_CustomerAddressInvestmentProperty_QNAME, CustomerAddressInvestmentProperty.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeAddressOccupancyOwnerOccupied }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "AddressOccupancyOwnerOccupied", substitutionHeadNamespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", substitutionHeadName = "AddressOccupancy")
    public JAXBElement<TypeAddressOccupancyOwnerOccupied> createAddressOccupancyOwnerOccupied(TypeAddressOccupancyOwnerOccupied value) {
        return new JAXBElement<TypeAddressOccupancyOwnerOccupied>(_AddressOccupancyOwnerOccupied_QNAME, TypeAddressOccupancyOwnerOccupied.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeAsset }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "Asset")
    public JAXBElement<TypeAsset> createAsset(TypeAsset value) {
        return new JAXBElement<TypeAsset>(_Asset_QNAME, TypeAsset.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeAddressOther }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "AddressOther")
    public JAXBElement<TypeAddressOther> createAddressOther(TypeAddressOther value) {
        return new JAXBElement<TypeAddressOther>(_AddressOther_QNAME, TypeAddressOther.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeAddressOccupancyTenant }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "AddressOccupancyTenant", substitutionHeadNamespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", substitutionHeadName = "AddressOccupancy")
    public JAXBElement<TypeAddressOccupancyTenant> createAddressOccupancyTenant(TypeAddressOccupancyTenant value) {
        return new JAXBElement<TypeAddressOccupancyTenant>(_AddressOccupancyTenant_QNAME, TypeAddressOccupancyTenant.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeCustomerAddress }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "CustomerAddress")
    public JAXBElement<TypeCustomerAddress> createCustomerAddress(TypeCustomerAddress value) {
        return new JAXBElement<TypeCustomerAddress>(_CustomerAddress_QNAME, TypeCustomerAddress.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeMunicipalAddressUSA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "MunicipalAddressUSA", substitutionHeadNamespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", substitutionHeadName = "MunicipalAddress")
    public JAXBElement<TypeMunicipalAddressUSA> createMunicipalAddressUSA(TypeMunicipalAddressUSA value) {
        return new JAXBElement<TypeMunicipalAddressUSA>(_MunicipalAddressUSA_QNAME, TypeMunicipalAddressUSA.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomerAddressPrimaryResidence }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "CustomerAddressPrimaryResidence", substitutionHeadNamespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", substitutionHeadName = "CustomerAddress")
    public JAXBElement<CustomerAddressPrimaryResidence> createCustomerAddressPrimaryResidence(CustomerAddressPrimaryResidence value) {
        return new JAXBElement<CustomerAddressPrimaryResidence>(_CustomerAddressPrimaryResidence_QNAME, CustomerAddressPrimaryResidence.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeCustomer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "CustomerBorrower", substitutionHeadNamespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", substitutionHeadName = "Customer")
    public JAXBElement<TypeCustomer> createCustomerBorrower(TypeCustomer value) {
        return new JAXBElement<TypeCustomer>(_CustomerBorrower_QNAME, TypeCustomer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeAddressUSA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "AddressUSA")
    public JAXBElement<TypeAddressUSA> createAddressUSA(TypeAddressUSA value) {
        return new JAXBElement<TypeAddressUSA>(_AddressUSA_QNAME, TypeAddressUSA.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypePostalAddress }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "PostalAddress")
    public JAXBElement<TypePostalAddress> createPostalAddress(TypePostalAddress value) {
        return new JAXBElement<TypePostalAddress>(_PostalAddress_QNAME, TypePostalAddress.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeAddressOccupancy }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "AddressOccupancy")
    public JAXBElement<TypeAddressOccupancy> createAddressOccupancy(TypeAddressOccupancy value) {
        return new JAXBElement<TypeAddressOccupancy>(_AddressOccupancy_QNAME, TypeAddressOccupancy.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeAssetOther }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "AssetOther", substitutionHeadNamespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", substitutionHeadName = "Asset")
    public JAXBElement<TypeAssetOther> createAssetOther(TypeAssetOther value) {
        return new JAXBElement<TypeAssetOther>(_AssetOther_QNAME, TypeAssetOther.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeCreditReportEquifax }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "CreditReportEquifax", substitutionHeadNamespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", substitutionHeadName = "CreditReport")
    public JAXBElement<TypeCreditReportEquifax> createCreditReportEquifax(TypeCreditReportEquifax value) {
        return new JAXBElement<TypeCreditReportEquifax>(_CreditReportEquifax_QNAME, TypeCreditReportEquifax.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeMunicipalAddressOther }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "MunicipalAddressOther", substitutionHeadNamespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", substitutionHeadName = "MunicipalAddress")
    public JAXBElement<TypeMunicipalAddressOther> createMunicipalAddressOther(TypeMunicipalAddressOther value) {
        return new JAXBElement<TypeMunicipalAddressOther>(_MunicipalAddressOther_QNAME, TypeMunicipalAddressOther.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeAddressOccupancyNone }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "AddressOccupancyNone", substitutionHeadNamespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", substitutionHeadName = "AddressOccupancy")
    public JAXBElement<TypeAddressOccupancyNone> createAddressOccupancyNone(TypeAddressOccupancyNone value) {
        return new JAXBElement<TypeAddressOccupancyNone>(_AddressOccupancyNone_QNAME, TypeAddressOccupancyNone.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomerAddressVacationProperty }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "CustomerAddressVacationProperty", substitutionHeadNamespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", substitutionHeadName = "CustomerAddress")
    public JAXBElement<CustomerAddressVacationProperty> createCustomerAddressVacationProperty(CustomerAddressVacationProperty value) {
        return new JAXBElement<CustomerAddressVacationProperty>(_CustomerAddressVacationProperty_QNAME, CustomerAddressVacationProperty.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeLiability }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "Liability")
    public JAXBElement<TypeLiability> createLiability(TypeLiability value) {
        return new JAXBElement<TypeLiability>(_Liability_QNAME, TypeLiability.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypePostalAddressPOBox }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "PostalAddressPOBox", substitutionHeadNamespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", substitutionHeadName = "PostalAddress")
    public JAXBElement<TypePostalAddressPOBox> createPostalAddressPOBox(TypePostalAddressPOBox value) {
        return new JAXBElement<TypePostalAddressPOBox>(_PostalAddressPOBox_QNAME, TypePostalAddressPOBox.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeCustomer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "Customer")
    public JAXBElement<TypeCustomer> createCustomer(TypeCustomer value) {
        return new JAXBElement<TypeCustomer>(_Customer_QNAME, TypeCustomer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeCreditBureau }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "CreditBureau")
    public JAXBElement<TypeCreditBureau> createCreditBureau(TypeCreditBureau value) {
        return new JAXBElement<TypeCreditBureau>(_CreditBureau_QNAME, TypeCreditBureau.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeApplicationAddressUSA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "ApplicationAddressUSA", substitutionHeadNamespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", substitutionHeadName = "ApplicationAddress")
    public JAXBElement<TypeApplicationAddressUSA> createApplicationAddressUSA(TypeApplicationAddressUSA value) {
        return new JAXBElement<TypeApplicationAddressUSA>(_ApplicationAddressUSA_QNAME, TypeApplicationAddressUSA.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeLiabilityOther }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "LiabilityOther", substitutionHeadNamespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", substitutionHeadName = "Liability")
    public JAXBElement<TypeLiabilityOther> createLiabilityOther(TypeLiabilityOther value) {
        return new JAXBElement<TypeLiabilityOther>(_LiabilityOther_QNAME, TypeLiabilityOther.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeCustomerAddressList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "CustomerAddressList")
    public JAXBElement<TypeCustomerAddressList> createCustomerAddressList(TypeCustomerAddressList value) {
        return new JAXBElement<TypeCustomerAddressList>(_CustomerAddressList_QNAME, TypeCustomerAddressList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeCustomerReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "CustomerReference")
    public JAXBElement<TypeCustomerReference> createCustomerReference(TypeCustomerReference value) {
        return new JAXBElement<TypeCustomerReference>(_CustomerReference_QNAME, TypeCustomerReference.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeAddressCanada }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "AddressCanada")
    public JAXBElement<TypeAddressCanada> createAddressCanada(TypeAddressCanada value) {
        return new JAXBElement<TypeAddressCanada>(_AddressCanada_QNAME, TypeAddressCanada.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeMunicipalAddress }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "MunicipalAddress")
    public JAXBElement<TypeMunicipalAddress> createMunicipalAddress(TypeMunicipalAddress value) {
        return new JAXBElement<TypeMunicipalAddress>(_MunicipalAddress_QNAME, TypeMunicipalAddress.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeCustomer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "CustomerGuarantor", substitutionHeadNamespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", substitutionHeadName = "Customer")
    public JAXBElement<TypeCustomer> createCustomerGuarantor(TypeCustomer value) {
        return new JAXBElement<TypeCustomer>(_CustomerGuarantor_QNAME, TypeCustomer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeAddressOccupancyRental }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "AddressOccupancyRental", substitutionHeadNamespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", substitutionHeadName = "AddressOccupancy")
    public JAXBElement<TypeAddressOccupancyRental> createAddressOccupancyRental(TypeAddressOccupancyRental value) {
        return new JAXBElement<TypeAddressOccupancyRental>(_AddressOccupancyRental_QNAME, TypeAddressOccupancyRental.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypePostalAddressStreetAddress }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "PostalAddressStreetAddress", substitutionHeadNamespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", substitutionHeadName = "PostalAddress")
    public JAXBElement<TypePostalAddressStreetAddress> createPostalAddressStreetAddress(TypePostalAddressStreetAddress value) {
        return new JAXBElement<TypePostalAddressStreetAddress>(_PostalAddressStreetAddress_QNAME, TypePostalAddressStreetAddress.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeAssetRealEstate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "AssetRealEstate", substitutionHeadNamespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", substitutionHeadName = "Asset")
    public JAXBElement<TypeAssetRealEstate> createAssetRealEstate(TypeAssetRealEstate value) {
        return new JAXBElement<TypeAssetRealEstate>(_AssetRealEstate_QNAME, TypeAssetRealEstate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeAddressOccupancyPartialOwnerOccupied }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "AddressOccupancyPartialOwnerOccupied", substitutionHeadNamespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", substitutionHeadName = "AddressOccupancy")
    public JAXBElement<TypeAddressOccupancyPartialOwnerOccupied> createAddressOccupancyPartialOwnerOccupied(TypeAddressOccupancyPartialOwnerOccupied value) {
        return new JAXBElement<TypeAddressOccupancyPartialOwnerOccupied>(_AddressOccupancyPartialOwnerOccupied_QNAME, TypeAddressOccupancyPartialOwnerOccupied.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeLiabilityRealEstate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "LiabilityRealEstate", substitutionHeadNamespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", substitutionHeadName = "Liability")
    public JAXBElement<TypeLiabilityRealEstate> createLiabilityRealEstate(TypeLiabilityRealEstate value) {
        return new JAXBElement<TypeLiabilityRealEstate>(_LiabilityRealEstate_QNAME, TypeLiabilityRealEstate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeMunicipalAddressCanada }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", name = "MunicipalAddressCanada", substitutionHeadNamespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", substitutionHeadName = "MunicipalAddress")
    public JAXBElement<TypeMunicipalAddressCanada> createMunicipalAddressCanada(TypeMunicipalAddressCanada value) {
        return new JAXBElement<TypeMunicipalAddressCanada>(_MunicipalAddressCanada_QNAME, TypeMunicipalAddressCanada.class, null, value);
    }

}
