//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.23 at 03:37:12 PM MDT 
//
@javax.xml.bind.annotation.XmlSchema(
		namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", 
		xmlns = {@javax.xml.bind.annotation.XmlNs(prefix="ns", namespaceURI="http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1")},
		elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED
)
package com.syml.morweb;
