//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.23 at 03:36:43 PM MDT 
//


package com.syml.morweb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}SubjectPropertyOccupancyOwnerOccupied"/>
 *           &lt;element ref="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}SubjectPropertyOccupancyPartialOwnerOccupied"/>
 *           &lt;element ref="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}SubjectPropertyOccupancyRental"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}LegalAddress" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element ref="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}Freehold"/>
 *           &lt;element ref="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}Leasehold"/>
 *           &lt;element ref="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}Condo"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}PropertyTax" minOccurs="0"/>
 *         &lt;element ref="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}PropertyAppraisal" minOccurs="0"/>
 *         &lt;element ref="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}SubjectPropertyAddress"/>
 *       &lt;/sequence>
 *       &lt;attribute name="occupancyPurpose" type="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typeSubjectPropertyOccupancyPurpose" />
 *       &lt;attribute name="MLSListed" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="MLSNumber">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typeStringNonEmpty">
 *             &lt;maxLength value="30"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="heatingType" type="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typeHeatingType" />
 *       &lt;attribute name="parkingType" type="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typeParkingType" />
 *       &lt;attribute name="yearBuilt">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}gYear">
 *             &lt;minInclusive value="0001"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="waterSupplyType" type="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typeWaterSupplyType" />
 *       &lt;attribute name="waterWasteType" type="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typeWaterWasteType" />
 *       &lt;attribute name="propertySize">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *             &lt;maxInclusive value="99999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="propertySizeUnits" type="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typeAreaMeasurementType" />
 *       &lt;attribute name="lotSize">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
 *             &lt;maxInclusive value="99999999999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="lotSizeUnits" type="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typeAreaMeasurementType" />
 *       &lt;attribute name="environmentalHazardIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="buildingConstructionType" type="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typeBuildingConstructionType" />
 *       &lt;attribute name="annualHeatingAmount">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;minInclusive value="0"/>
 *             &lt;maxInclusive value="1234567.99"/>
 *             &lt;fractionDigits value="2"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="numberOfUnitsTotal">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *             &lt;maxInclusive value="99999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="numberOfUnitsRented">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
 *             &lt;maxInclusive value="99999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="propertyType" type="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typePropertyTypeType" />
 *       &lt;attribute name="propertyDescriptionType" type="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typePropertyDescriptionType" />
 *       &lt;attribute name="propertyUsageType" type="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typePropertyUsageType" />
 *       &lt;attribute name="selfBuildIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="propertyZoningType" type="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typePropertyZoningType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "subjectPropertyOccupancyOwnerOccupied",
    "subjectPropertyOccupancyPartialOwnerOccupied",
    "subjectPropertyOccupancyRental",
    "legalAddress",
    "freehold",
    "leasehold",
    "condo",
    "propertyTax",
    "propertyAppraisal",
    "subjectPropertyAddress"
})
@XmlRootElement(name = "SubjectProperty")
public class SubjectProperty {

    @XmlElement(name = "SubjectPropertyOccupancyOwnerOccupied")
    protected SubjectPropertyOccupancyOwnerOccupied subjectPropertyOccupancyOwnerOccupied;
    @XmlElement(name = "SubjectPropertyOccupancyPartialOwnerOccupied")
    protected SubjectPropertyOccupancyPartialOwnerOccupied subjectPropertyOccupancyPartialOwnerOccupied;
    @XmlElement(name = "SubjectPropertyOccupancyRental")
    protected SubjectPropertyOccupancyRental subjectPropertyOccupancyRental;
    @XmlElement(name = "LegalAddress")
    protected LegalAddress legalAddress;
    @XmlElement(name = "Freehold")
    protected Freehold freehold;
    @XmlElement(name = "Leasehold")
    protected Leasehold leasehold;
    @XmlElement(name = "Condo")
    protected Condo condo;
    @XmlElement(name = "PropertyTax")
    protected PropertyTax propertyTax;
    @XmlElement(name = "PropertyAppraisal")
    protected PropertyAppraisal propertyAppraisal;
    @XmlElement(name = "SubjectPropertyAddress", required = true)
    protected SubjectPropertyAddress subjectPropertyAddress;
    @XmlAttribute(name = "occupancyPurpose")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String occupancyPurpose;
    @XmlAttribute(name = "MLSListed")
    protected Boolean mlsListed;
    @XmlAttribute(name = "MLSNumber")
    protected String mlsNumber;
    @XmlAttribute(name = "heatingType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String heatingType;
    @XmlAttribute(name = "parkingType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String parkingType;
    @XmlAttribute(name = "yearBuilt")
    protected XMLGregorianCalendar yearBuilt;
    @XmlAttribute(name = "waterSupplyType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String waterSupplyType;
    @XmlAttribute(name = "waterWasteType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String waterWasteType;
    @XmlAttribute(name = "propertySize")
    protected Integer propertySize;
    @XmlAttribute(name = "propertySizeUnits")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String propertySizeUnits;
    @XmlAttribute(name = "lotSize")
    protected Long lotSize;
    @XmlAttribute(name = "lotSizeUnits")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String lotSizeUnits;
    @XmlAttribute(name = "environmentalHazardIndicator")
    protected Boolean environmentalHazardIndicator;
    @XmlAttribute(name = "buildingConstructionType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String buildingConstructionType;
    @XmlAttribute(name = "annualHeatingAmount")
    protected BigDecimal annualHeatingAmount;
    @XmlAttribute(name = "numberOfUnitsTotal")
    protected Integer numberOfUnitsTotal;
    @XmlAttribute(name = "numberOfUnitsRented")
    protected Integer numberOfUnitsRented;
    @XmlAttribute(name = "propertyType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String propertyType;
    @XmlAttribute(name = "propertyDescriptionType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String propertyDescriptionType;
    @XmlAttribute(name = "propertyUsageType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String propertyUsageType;
    @XmlAttribute(name = "selfBuildIndicator")
    protected Boolean selfBuildIndicator;
    @XmlAttribute(name = "propertyZoningType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String propertyZoningType;

    /**
     * Gets the value of the subjectPropertyOccupancyOwnerOccupied property.
     * 
     * @return
     *     possible object is
     *     {@link SubjectPropertyOccupancyOwnerOccupied }
     *     
     */
    public SubjectPropertyOccupancyOwnerOccupied getSubjectPropertyOccupancyOwnerOccupied() {
        return subjectPropertyOccupancyOwnerOccupied;
    }

    /**
     * Sets the value of the subjectPropertyOccupancyOwnerOccupied property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubjectPropertyOccupancyOwnerOccupied }
     *     
     */
    public void setSubjectPropertyOccupancyOwnerOccupied(SubjectPropertyOccupancyOwnerOccupied value) {
        this.subjectPropertyOccupancyOwnerOccupied = value;
    }

    /**
     * Gets the value of the subjectPropertyOccupancyPartialOwnerOccupied property.
     * 
     * @return
     *     possible object is
     *     {@link SubjectPropertyOccupancyPartialOwnerOccupied }
     *     
     */
    public SubjectPropertyOccupancyPartialOwnerOccupied getSubjectPropertyOccupancyPartialOwnerOccupied() {
        return subjectPropertyOccupancyPartialOwnerOccupied;
    }

    /**
     * Sets the value of the subjectPropertyOccupancyPartialOwnerOccupied property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubjectPropertyOccupancyPartialOwnerOccupied }
     *     
     */
    public void setSubjectPropertyOccupancyPartialOwnerOccupied(SubjectPropertyOccupancyPartialOwnerOccupied value) {
        this.subjectPropertyOccupancyPartialOwnerOccupied = value;
    }

    /**
     * Gets the value of the subjectPropertyOccupancyRental property.
     * 
     * @return
     *     possible object is
     *     {@link SubjectPropertyOccupancyRental }
     *     
     */
    public SubjectPropertyOccupancyRental getSubjectPropertyOccupancyRental() {
        return subjectPropertyOccupancyRental;
    }

    /**
     * Sets the value of the subjectPropertyOccupancyRental property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubjectPropertyOccupancyRental }
     *     
     */
    public void setSubjectPropertyOccupancyRental(SubjectPropertyOccupancyRental value) {
        this.subjectPropertyOccupancyRental = value;
    }

    /**
     * Gets the value of the legalAddress property.
     * 
     * @return
     *     possible object is
     *     {@link LegalAddress }
     *     
     */
    public LegalAddress getLegalAddress() {
        return legalAddress;
    }

    /**
     * Sets the value of the legalAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link LegalAddress }
     *     
     */
    public void setLegalAddress(LegalAddress value) {
        this.legalAddress = value;
    }

    /**
     * Gets the value of the freehold property.
     * 
     * @return
     *     possible object is
     *     {@link Freehold }
     *     
     */
    public Freehold getFreehold() {
        return freehold;
    }

    /**
     * Sets the value of the freehold property.
     * 
     * @param value
     *     allowed object is
     *     {@link Freehold }
     *     
     */
    public void setFreehold(Freehold value) {
        this.freehold = value;
    }

    /**
     * Gets the value of the leasehold property.
     * 
     * @return
     *     possible object is
     *     {@link Leasehold }
     *     
     */
    public Leasehold getLeasehold() {
        return leasehold;
    }

    /**
     * Sets the value of the leasehold property.
     * 
     * @param value
     *     allowed object is
     *     {@link Leasehold }
     *     
     */
    public void setLeasehold(Leasehold value) {
        this.leasehold = value;
    }

    /**
     * Gets the value of the condo property.
     * 
     * @return
     *     possible object is
     *     {@link Condo }
     *     
     */
    public Condo getCondo() {
        return condo;
    }

    /**
     * Sets the value of the condo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Condo }
     *     
     */
    public void setCondo(Condo value) {
        this.condo = value;
    }

    /**
     * Gets the value of the propertyTax property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyTax }
     *     
     */
    public PropertyTax getPropertyTax() {
        return propertyTax;
    }

    /**
     * Sets the value of the propertyTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyTax }
     *     
     */
    public void setPropertyTax(PropertyTax value) {
        this.propertyTax = value;
    }

    /**
     * Gets the value of the propertyAppraisal property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyAppraisal }
     *     
     */
    public PropertyAppraisal getPropertyAppraisal() {
        return propertyAppraisal;
    }

    /**
     * Sets the value of the propertyAppraisal property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyAppraisal }
     *     
     */
    public void setPropertyAppraisal(PropertyAppraisal value) {
        this.propertyAppraisal = value;
    }

    /**
     * Gets the value of the subjectPropertyAddress property.
     * 
     * @return
     *     possible object is
     *     {@link SubjectPropertyAddress }
     *     
     */
    public SubjectPropertyAddress getSubjectPropertyAddress() {
        return subjectPropertyAddress;
    }

    /**
     * Sets the value of the subjectPropertyAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubjectPropertyAddress }
     *     
     */
    public void setSubjectPropertyAddress(SubjectPropertyAddress value) {
        this.subjectPropertyAddress = value;
    }

    /**
     * Gets the value of the occupancyPurpose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOccupancyPurpose() {
        return occupancyPurpose;
    }

    /**
     * Sets the value of the occupancyPurpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOccupancyPurpose(String value) {
        this.occupancyPurpose = value;
    }

    /**
     * Gets the value of the mlsListed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMLSListed() {
        return mlsListed;
    }

    /**
     * Sets the value of the mlsListed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMLSListed(Boolean value) {
        this.mlsListed = value;
    }

    /**
     * Gets the value of the mlsNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMLSNumber() {
        return mlsNumber;
    }

    /**
     * Sets the value of the mlsNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMLSNumber(String value) {
        this.mlsNumber = value;
    }

    /**
     * Gets the value of the heatingType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeatingType() {
        return heatingType;
    }

    /**
     * Sets the value of the heatingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeatingType(String value) {
        this.heatingType = value;
    }

    /**
     * Gets the value of the parkingType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParkingType() {
        return parkingType;
    }

    /**
     * Sets the value of the parkingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParkingType(String value) {
        this.parkingType = value;
    }

    /**
     * Gets the value of the yearBuilt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getYearBuilt() {
        return yearBuilt;
    }

    /**
     * Sets the value of the yearBuilt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setYearBuilt(XMLGregorianCalendar value) {
        this.yearBuilt = value;
    }

    /**
     * Gets the value of the waterSupplyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWaterSupplyType() {
        return waterSupplyType;
    }

    /**
     * Sets the value of the waterSupplyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWaterSupplyType(String value) {
        this.waterSupplyType = value;
    }

    /**
     * Gets the value of the waterWasteType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWaterWasteType() {
        return waterWasteType;
    }

    /**
     * Sets the value of the waterWasteType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWaterWasteType(String value) {
        this.waterWasteType = value;
    }

    /**
     * Gets the value of the propertySize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPropertySize() {
        return propertySize;
    }

    /**
     * Sets the value of the propertySize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPropertySize(Integer value) {
        this.propertySize = value;
    }

    /**
     * Gets the value of the propertySizeUnits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertySizeUnits() {
        return propertySizeUnits;
    }

    /**
     * Sets the value of the propertySizeUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertySizeUnits(String value) {
        this.propertySizeUnits = value;
    }

    /**
     * Gets the value of the lotSize property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLotSize() {
        return lotSize;
    }

    /**
     * Sets the value of the lotSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLotSize(Long value) {
        this.lotSize = value;
    }

    /**
     * Gets the value of the lotSizeUnits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLotSizeUnits() {
        return lotSizeUnits;
    }

    /**
     * Sets the value of the lotSizeUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLotSizeUnits(String value) {
        this.lotSizeUnits = value;
    }

    /**
     * Gets the value of the environmentalHazardIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnvironmentalHazardIndicator() {
        return environmentalHazardIndicator;
    }

    /**
     * Sets the value of the environmentalHazardIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnvironmentalHazardIndicator(Boolean value) {
        this.environmentalHazardIndicator = value;
    }

    /**
     * Gets the value of the buildingConstructionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuildingConstructionType() {
        return buildingConstructionType;
    }

    /**
     * Sets the value of the buildingConstructionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuildingConstructionType(String value) {
        this.buildingConstructionType = value;
    }

    /**
     * Gets the value of the annualHeatingAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAnnualHeatingAmount() {
        return annualHeatingAmount;
    }

    /**
     * Sets the value of the annualHeatingAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAnnualHeatingAmount(BigDecimal value) {
        this.annualHeatingAmount = value;
    }

    /**
     * Gets the value of the numberOfUnitsTotal property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumberOfUnitsTotal() {
        return numberOfUnitsTotal;
    }

    /**
     * Sets the value of the numberOfUnitsTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberOfUnitsTotal(Integer value) {
        this.numberOfUnitsTotal = value;
    }

    /**
     * Gets the value of the numberOfUnitsRented property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumberOfUnitsRented() {
        return numberOfUnitsRented;
    }

    /**
     * Sets the value of the numberOfUnitsRented property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberOfUnitsRented(Integer value) {
        this.numberOfUnitsRented = value;
    }

    /**
     * Gets the value of the propertyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyType() {
        return propertyType;
    }

    /**
     * Sets the value of the propertyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyType(String value) {
        this.propertyType = value;
    }

    /**
     * Gets the value of the propertyDescriptionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyDescriptionType() {
        return propertyDescriptionType;
    }

    /**
     * Sets the value of the propertyDescriptionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyDescriptionType(String value) {
        this.propertyDescriptionType = value;
    }

    /**
     * Gets the value of the propertyUsageType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyUsageType() {
        return propertyUsageType;
    }

    /**
     * Sets the value of the propertyUsageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyUsageType(String value) {
        this.propertyUsageType = value;
    }

    /**
     * Gets the value of the selfBuildIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSelfBuildIndicator() {
        return selfBuildIndicator;
    }

    /**
     * Sets the value of the selfBuildIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSelfBuildIndicator(Boolean value) {
        this.selfBuildIndicator = value;
    }

    /**
     * Gets the value of the propertyZoningType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyZoningType() {
        return propertyZoningType;
    }

    /**
     * Sets the value of the propertyZoningType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyZoningType(String value) {
        this.propertyZoningType = value;
    }

}
