//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.23 at 03:36:43 PM MDT 
//


package com.syml.morweb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeCustomerAddressList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeCustomerAddressList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}CustomerAddress" maxOccurs="99999" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeCustomerAddressList", propOrder = {
    "customerAddress"
})
public class TypeCustomerAddressList {

    @XmlElementRef(name = "CustomerAddress", namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", type = JAXBElement.class, required = false)
    protected List<JAXBElement<? extends TypeCustomerAddress>> customerAddress;

    /**
     * Gets the value of the customerAddress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the customerAddress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustomerAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link CustomerAddressInvestmentProperty }{@code >}
     * {@link JAXBElement }{@code <}{@link TypeCustomerAddress }{@code >}
     * {@link JAXBElement }{@code <}{@link CustomerAddressCorrespondence }{@code >}
     * {@link JAXBElement }{@code <}{@link CustomerAddressPreviousResidence }{@code >}
     * {@link JAXBElement }{@code <}{@link CustomerAddressSecondaryResidence }{@code >}
     * {@link JAXBElement }{@code <}{@link CustomerAddressVacationProperty }{@code >}
     * {@link JAXBElement }{@code <}{@link CustomerAddressPrimaryResidence }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends TypeCustomerAddress>> getCustomerAddress() {
        if (customerAddress == null) {
            customerAddress = new ArrayList<JAXBElement<? extends TypeCustomerAddress>>();
        }
        return this.customerAddress;
    }

}

