//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.23 at 03:36:43 PM MDT 
//


package com.syml.morweb;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;

import com.syml.domain.Applicant;
import com.syml.domain.Asset;
import com.syml.domain.Property;


/**
 * <p>Java class for typeAssetOther complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeAssetOther">
 *   &lt;complexContent>
 *     &lt;extension base="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typeAsset">
 *       &lt;attribute name="assetType" use="required" type="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typeAssetOtherType" />
 *       &lt;attribute name="location">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typeStringNonEmpty">
 *             &lt;maxLength value="50"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="maturityDate" type="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typeDate" />
 *       &lt;attribute name="addtionalAssetHolders">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typeStringNonEmpty">
 *             &lt;maxLength value="255"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="description">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typeStringNonEmpty">
 *             &lt;maxLength value="50"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeAssetOther")
public class TypeAssetOther extends TypeAsset {

    @XmlAttribute(name = "assetType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String assetType;
    @XmlAttribute(name = "location")
    protected String location;
    @XmlAttribute(name = "maturityDate")
    protected XMLGregorianCalendar maturityDate;
    @XmlAttribute(name = "addtionalAssetHolders")
    protected String addtionalAssetHolders;
    @XmlAttribute(name = "description")
    protected String description;

    @XmlTransient
    private Asset asset;
    @XmlTransient
	private Property property;

    public TypeAssetOther() {
    }
    
    public TypeAssetOther(int key, Asset assetSyml, Applicant applicant) {
    	asset = assetSyml;
    	
    	String keyString = "APPL-" + applicant.getId() + "_AST.OT-" + key;
    	this.setKey(keyString);
    	
    	
    	// Asset Type  (10 Bank Account
//   			 20 Insurance Policy 
//   			30 RRSP 
//   			40 Vehicle 
//   			60 Investments 
//   			99 Other)
    	if (asset.assetType.contains("1")){
    		// Vehicle
    		this.assetType = "40";
    	}
    	else if (asset.assetType.contains("2")){
    		// RSP
    		this.assetType = "30";
    	}
    	else if (asset.assetType.contains("3")){
    		// NonRSP
    		this.assetType = "60";
    	}
    	else {
    		// Other 
    		this.assetType = "99";
    	}
    	this.description = asset.name;
    	this.value = BigDecimal.valueOf(asset.value);	

    }
    
    public TypeAssetOther(int key, Property propertySyml, Applicant applicant) {
    	property = propertySyml;
    	
    	String keyString = "APPL-" + applicant.getId() + "_AST.OT-" + key;
    	this.setKey(keyString);
    	this.assetType = "99";
    	this.description = property.name;
    	this.value = BigDecimal.valueOf(property.value);
    }

    /**
     * Gets the value of the assetType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssetType() {
        return assetType;
    }

    /**
     * Sets the value of the assetType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssetType(String value) {
        this.assetType = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the maturityDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMaturityDate() {
        return maturityDate;
    }

    /**
     * Sets the value of the maturityDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMaturityDate(XMLGregorianCalendar value) {
        this.maturityDate = value;
    }

    /**
     * Gets the value of the addtionalAssetHolders property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddtionalAssetHolders() {
        return addtionalAssetHolders;
    }

    /**
     * Sets the value of the addtionalAssetHolders property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddtionalAssetHolders(String value) {
        this.addtionalAssetHolders = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

	public Asset getAsset() {
		return asset;
	}

	public void setAsset(Asset asset) {
		this.asset = asset;
	}

	public Property getProperty() {
		return property;
	}

	public void setProperty(Property property) {
		this.property = property;
	}

}
