//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.17 at 04:35:20 AM ICT 
//


package com.syml.morweb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for typeMunicipalAddress complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeMunicipalAddress">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}PostalAddress"/>
 *       &lt;/choice>
 *       &lt;attGroup ref="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}attributesMunicipalAddress"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeMunicipalAddress", propOrder = {
    "postalAddress"
})
@XmlSeeAlso({
    TypeApplicationAddress.class,
    TypeMunicipalAddressUSA.class,
    TypeMunicipalAddressOther.class,
    TypeMunicipalAddressCanada.class,
    TypeAddress.class
})
public abstract class TypeMunicipalAddress {

    @XmlElementRef(name = "PostalAddress", namespace = "http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1", type = JAXBElement.class, required = false)
    protected JAXBElement<? extends TypePostalAddress> postalAddress;
    @XmlAttribute(name = "cityTown")
    protected String cityTown;
    @XmlAttribute(name = "provinceCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String provinceCode;
    @XmlAttribute(name = "postalCode")
    protected String postalCode;
    @XmlAttribute(name = "countryCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String countryCode;

    /**
     * Gets the value of the postalAddress property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TypePostalAddressPOBox }{@code >}
     *     {@link JAXBElement }{@code <}{@link TypePostalAddressStreetAddress }{@code >}
     *     {@link JAXBElement }{@code <}{@link TypePostalAddress }{@code >}
     *     
     */
    public JAXBElement<? extends TypePostalAddress> getPostalAddress() {
        return postalAddress;
    }

    /**
     * Sets the value of the postalAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TypePostalAddressPOBox }{@code >}
     *     {@link JAXBElement }{@code <}{@link TypePostalAddressStreetAddress }{@code >}
     *     {@link JAXBElement }{@code <}{@link TypePostalAddress }{@code >}
     *     
     */
    public void setPostalAddress(JAXBElement<? extends TypePostalAddress> value) {
        this.postalAddress = value;
    }

    /**
     * Gets the value of the cityTown property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCityTown() {
        return cityTown;
    }

    /**
     * Sets the value of the cityTown property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCityTown(String value) {
        this.cityTown = value;
    }

    /**
     * Gets the value of the provinceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * Sets the value of the provinceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvinceCode(String value) {
        this.provinceCode = value;
    }

    /**
     * Gets the value of the postalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * Sets the value of the postalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostalCode(String value) {
        this.postalCode = value;
    }

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCode(String value) {
        this.countryCode = value;
    }

}
