//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.23 at 03:36:43 PM MDT 
//


package com.syml.morweb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for typeLiabilityRealEstate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeLiabilityRealEstate">
 *   &lt;complexContent>
 *     &lt;extension base="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typeLiability">
 *       &lt;attribute name="accountNumber">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typeStringNonEmpty">
 *             &lt;maxLength value="20"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="othersResponsible" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="othersResponsibleDetails">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typeStringNonEmpty">
 *             &lt;maxLength value="255"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="monthlyRepayment" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;minInclusive value="0"/>
 *             &lt;maxInclusive value="9999999.99"/>
 *             &lt;fractionDigits value="2"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="originalLoanAmount" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;minInclusive value="0"/>
 *             &lt;maxInclusive value="9999999.99"/>
 *             &lt;fractionDigits value="2"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="outstandingBalance" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;minInclusive value="0"/>
 *             &lt;maxInclusive value="9999999.99"/>
 *             &lt;fractionDigits value="2"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="closingDate" type="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typeDate" />
 *       &lt;attribute name="lenderName" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typeStringNonEmpty">
 *             &lt;minLength value="1"/>
 *             &lt;maxLength value="44"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="chargeType" use="required" type="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typeChargeType" />
 *       &lt;attribute name="repaymentType" use="required" type="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typeLoanRepaymentType" />
 *       &lt;attribute name="redemptionStatus" use="required" type="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typeLoanRedemptionStatus" />
 *       &lt;attribute name="mortgageInsurer" type="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typeMortgageInsurerType" />
 *       &lt;attribute name="insuredAmount">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;minInclusive value="0"/>
 *             &lt;totalDigits value="6"/>
 *             &lt;fractionDigits value="0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="insurancePremium">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;minInclusive value="0"/>
 *             &lt;totalDigits value="6"/>
 *             &lt;fractionDigits value="0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="insuranceCertificateNumber">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typeStringNonEmpty">
 *             &lt;maxLength value="10"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeLiabilityRealEstate")
public class TypeLiabilityRealEstate
    extends TypeLiability
{

    @XmlAttribute(name = "accountNumber")
    protected String accountNumber;
    @XmlAttribute(name = "othersResponsible")
    protected Boolean othersResponsible;
    @XmlAttribute(name = "othersResponsibleDetails")
    protected String othersResponsibleDetails;
    @XmlAttribute(name = "monthlyRepayment", required = true)
    protected BigDecimal monthlyRepayment;
    @XmlAttribute(name = "originalLoanAmount", required = true)
    protected BigDecimal originalLoanAmount;
    @XmlAttribute(name = "outstandingBalance", required = true)
    protected BigDecimal outstandingBalance;
    @XmlAttribute(name = "closingDate")
    protected XMLGregorianCalendar closingDate;
    @XmlAttribute(name = "lenderName", required = true)
    protected String lenderName;
    @XmlAttribute(name = "chargeType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String chargeType;
    @XmlAttribute(name = "repaymentType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String repaymentType;
    @XmlAttribute(name = "redemptionStatus", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String redemptionStatus;
    @XmlAttribute(name = "mortgageInsurer")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String mortgageInsurer;
    @XmlAttribute(name = "insuredAmount")
    protected BigDecimal insuredAmount;
    @XmlAttribute(name = "insurancePremium")
    protected BigDecimal insurancePremium;
    @XmlAttribute(name = "insuranceCertificateNumber")
    protected String insuranceCertificateNumber;

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the othersResponsible property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOthersResponsible() {
        return othersResponsible;
    }

    /**
     * Sets the value of the othersResponsible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOthersResponsible(Boolean value) {
        this.othersResponsible = value;
    }

    /**
     * Gets the value of the othersResponsibleDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOthersResponsibleDetails() {
        return othersResponsibleDetails;
    }

    /**
     * Sets the value of the othersResponsibleDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOthersResponsibleDetails(String value) {
        this.othersResponsibleDetails = value;
    }

    /**
     * Gets the value of the monthlyRepayment property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMonthlyRepayment() {
        return monthlyRepayment;
    }

    /**
     * Sets the value of the monthlyRepayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMonthlyRepayment(BigDecimal value) {
        this.monthlyRepayment = value;
    }

    /**
     * Gets the value of the originalLoanAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOriginalLoanAmount() {
        return originalLoanAmount;
    }

    /**
     * Sets the value of the originalLoanAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOriginalLoanAmount(BigDecimal value) {
        this.originalLoanAmount = value;
    }

    /**
     * Gets the value of the outstandingBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOutstandingBalance() {
        return outstandingBalance;
    }

    /**
     * Sets the value of the outstandingBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOutstandingBalance(BigDecimal value) {
        this.outstandingBalance = value;
    }

    /**
     * Gets the value of the closingDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getClosingDate() {
        return closingDate;
    }

    /**
     * Sets the value of the closingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setClosingDate(XMLGregorianCalendar value) {
        this.closingDate = value;
    }

    /**
     * Gets the value of the lenderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLenderName() {
        return lenderName;
    }

    /**
     * Sets the value of the lenderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLenderName(String value) {
        this.lenderName = value;
    }

    /**
     * Gets the value of the chargeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChargeType() {
        return chargeType;
    }

    /**
     * Sets the value of the chargeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChargeType(String value) {
        this.chargeType = value;
    }

    /**
     * Gets the value of the repaymentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepaymentType() {
        return repaymentType;
    }

    /**
     * Sets the value of the repaymentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepaymentType(String value) {
        this.repaymentType = value;
    }

    /**
     * Gets the value of the redemptionStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRedemptionStatus() {
        return redemptionStatus;
    }

    /**
     * Sets the value of the redemptionStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRedemptionStatus(String value) {
        this.redemptionStatus = value;
    }

    /**
     * Gets the value of the mortgageInsurer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMortgageInsurer() {
        return mortgageInsurer;
    }

    /**
     * Sets the value of the mortgageInsurer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMortgageInsurer(String value) {
        this.mortgageInsurer = value;
    }

    /**
     * Gets the value of the insuredAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInsuredAmount() {
        return insuredAmount;
    }

    /**
     * Sets the value of the insuredAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInsuredAmount(BigDecimal value) {
        this.insuredAmount = value;
    }

    /**
     * Gets the value of the insurancePremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInsurancePremium() {
        return insurancePremium;
    }

    /**
     * Sets the value of the insurancePremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInsurancePremium(BigDecimal value) {
        this.insurancePremium = value;
    }

    /**
     * Gets the value of the insuranceCertificateNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsuranceCertificateNumber() {
        return insuranceCertificateNumber;
    }

    /**
     * Sets the value of the insuranceCertificateNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsuranceCertificateNumber(String value) {
        this.insuranceCertificateNumber = value;
    }

}
