//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.23 at 03:36:43 PM MDT 
//


package com.syml.morweb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for typeCustomerAddress complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeCustomerAddress">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}CustomerReference" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}CustomerLiabilityRealEstate" maxOccurs="99999" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element ref="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}AddressOccupancyNone"/>
 *           &lt;element ref="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}AddressOccupancyOwnerOccupied"/>
 *           &lt;element ref="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}AddressOccupancyPartialOwnerOccupied"/>
 *           &lt;element ref="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}AddressOccupancyRental"/>
 *           &lt;element ref="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}AddressOccupancyTenant"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="refkeyAddress" use="required" type="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typeReferenceKey" />
 *       &lt;attribute name="fromDate" type="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typeDate" />
 *       &lt;attribute name="toDate" type="{http://MSC.IntegrationService.Schemas.MorWEB.BDI.Request.1}typeDate" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeCustomerAddress", propOrder = {
    "customerReference",
    "customerLiabilityRealEstate",
    "addressOccupancyNone",
    "addressOccupancyOwnerOccupied",
    "addressOccupancyPartialOwnerOccupied",
    "addressOccupancyRental",
    "addressOccupancyTenant"
})
@XmlSeeAlso({
    CustomerAddressCorrespondence.class,
    CustomerAddressSecondaryResidence.class,
    CustomerAddressVacationProperty.class,
    CustomerAddressPrimaryResidence.class,
    CustomerAddressInvestmentProperty.class,
    CustomerAddressPreviousResidence.class
})
public abstract class TypeCustomerAddress {

    @XmlElement(name = "CustomerReference", required = true)
    protected List<TypeCustomerReference> customerReference;
    @XmlElement(name = "CustomerLiabilityRealEstate")
    protected List<CustomerLiabilityRealEstate> customerLiabilityRealEstate;
    @XmlElement(name = "AddressOccupancyNone")
    protected TypeAddressOccupancyNone addressOccupancyNone;
    @XmlElement(name = "AddressOccupancyOwnerOccupied")
    protected TypeAddressOccupancyOwnerOccupied addressOccupancyOwnerOccupied;
    @XmlElement(name = "AddressOccupancyPartialOwnerOccupied")
    protected TypeAddressOccupancyPartialOwnerOccupied addressOccupancyPartialOwnerOccupied;
    @XmlElement(name = "AddressOccupancyRental")
    protected TypeAddressOccupancyRental addressOccupancyRental;
    @XmlElement(name = "AddressOccupancyTenant")
    protected TypeAddressOccupancyTenant addressOccupancyTenant;
    @XmlAttribute(name = "refkeyAddress", required = true)
    protected String refkeyAddress;
    @XmlAttribute(name = "fromDate")
    protected XMLGregorianCalendar fromDate;
    @XmlAttribute(name = "toDate")
    protected XMLGregorianCalendar toDate;

    /**
     * Gets the value of the customerReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the customerReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustomerReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypeCustomerReference }
     * 
     * 
     */
    public List<TypeCustomerReference> getCustomerReference() {
        if (customerReference == null) {
            customerReference = new ArrayList<TypeCustomerReference>();
        }
        return this.customerReference;
    }

    /**
     * Gets the value of the customerLiabilityRealEstate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the customerLiabilityRealEstate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustomerLiabilityRealEstate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CustomerLiabilityRealEstate }
     * 
     * 
     */
    public List<CustomerLiabilityRealEstate> getCustomerLiabilityRealEstate() {
        if (customerLiabilityRealEstate == null) {
            customerLiabilityRealEstate = new ArrayList<CustomerLiabilityRealEstate>();
        }
        return this.customerLiabilityRealEstate;
    }

    /**
     * Gets the value of the addressOccupancyNone property.
     * 
     * @return
     *     possible object is
     *     {@link TypeAddressOccupancyNone }
     *     
     */
    public TypeAddressOccupancyNone getAddressOccupancyNone() {
        return addressOccupancyNone;
    }

    /**
     * Sets the value of the addressOccupancyNone property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeAddressOccupancyNone }
     *     
     */
    public void setAddressOccupancyNone(TypeAddressOccupancyNone value) {
        this.addressOccupancyNone = value;
    }

    /**
     * Gets the value of the addressOccupancyOwnerOccupied property.
     * 
     * @return
     *     possible object is
     *     {@link TypeAddressOccupancyOwnerOccupied }
     *     
     */
    public TypeAddressOccupancyOwnerOccupied getAddressOccupancyOwnerOccupied() {
        return addressOccupancyOwnerOccupied;
    }

    /**
     * Sets the value of the addressOccupancyOwnerOccupied property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeAddressOccupancyOwnerOccupied }
     *     
     */
    public void setAddressOccupancyOwnerOccupied(TypeAddressOccupancyOwnerOccupied value) {
        this.addressOccupancyOwnerOccupied = value;
    }

    /**
     * Gets the value of the addressOccupancyPartialOwnerOccupied property.
     * 
     * @return
     *     possible object is
     *     {@link TypeAddressOccupancyPartialOwnerOccupied }
     *     
     */
    public TypeAddressOccupancyPartialOwnerOccupied getAddressOccupancyPartialOwnerOccupied() {
        return addressOccupancyPartialOwnerOccupied;
    }

    /**
     * Sets the value of the addressOccupancyPartialOwnerOccupied property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeAddressOccupancyPartialOwnerOccupied }
     *     
     */
    public void setAddressOccupancyPartialOwnerOccupied(TypeAddressOccupancyPartialOwnerOccupied value) {
        this.addressOccupancyPartialOwnerOccupied = value;
    }

    /**
     * Gets the value of the addressOccupancyRental property.
     * 
     * @return
     *     possible object is
     *     {@link TypeAddressOccupancyRental }
     *     
     */
    public TypeAddressOccupancyRental getAddressOccupancyRental() {
        return addressOccupancyRental;
    }

    /**
     * Sets the value of the addressOccupancyRental property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeAddressOccupancyRental }
     *     
     */
    public void setAddressOccupancyRental(TypeAddressOccupancyRental value) {
        this.addressOccupancyRental = value;
    }

    /**
     * Gets the value of the addressOccupancyTenant property.
     * 
     * @return
     *     possible object is
     *     {@link TypeAddressOccupancyTenant }
     *     
     */
    public TypeAddressOccupancyTenant getAddressOccupancyTenant() {
        return addressOccupancyTenant;
    }

    /**
     * Sets the value of the addressOccupancyTenant property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeAddressOccupancyTenant }
     *     
     */
    public void setAddressOccupancyTenant(TypeAddressOccupancyTenant value) {
        this.addressOccupancyTenant = value;
    }

    /**
     * Gets the value of the refkeyAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefkeyAddress() {
        return refkeyAddress;
    }

    /**
     * Sets the value of the refkeyAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefkeyAddress(String value) {
        this.refkeyAddress = value;
    }

    /**
     * Gets the value of the fromDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFromDate() {
        return fromDate;
    }

    /**
     * Sets the value of the fromDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFromDate(XMLGregorianCalendar value) {
        this.fromDate = value;
    }

    /**
     * Gets the value of the toDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getToDate() {
        return toDate;
    }

    /**
     * Sets the value of the toDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setToDate(XMLGregorianCalendar value) {
        this.toDate = value;
    }

}
